### ISSUE TITLE
Unity 6 Preview Build Support for Android (and possibly iOs)

### ISSUE THREAD

**Issue by kenofori** [PlayEveryWare/eos_plugin_for_unity#681] opened 2024-05-20 12:50 UTC
Whenever I try to build for Android I get following error and Gemini Ai says its due to EOS:

The Gradle build system, which Unity uses for Android builds, requires each module in your project to have a unique namespace. This namespace helps to avoid conflicts between different modules and libraries. However, it appears that one of your modules (eos_dependencies.androidlib) is missing this namespace specification.

Please advise

**Expected behavior**
It should build for Android

**Desktop (please complete the following information):**
 - OS: Windows 11, but targetting for Android
 - Editor
 - Unity 6 Preview 2
 - Latest Stable EOS plugin

**Additional context**
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':unityLibrary:eos_dependencies.androidlib'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.
     
     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 7s
]
stdout[

> Configure project :unityLibrary
Variant 'debug', will keep symbols in binaries for:
  'libunity.so'
  'libil2cpp.so'
  'libmain.so'
Variant 'release', symbols will be stripped from binaries.

> Configure project :launcher
Variant 'debug', will keep symbols in binaries for:
  'libunity.so'
  'libil2cpp.so'
  'libmain.so'
Variant 'release', symbols will be stripped from binaries.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.4/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
]

**Comment by paulhazen** [comment] 2024-05-20 18:14
Hi @kenofori. Unfortunately, we do not currently support Unity version `2023.3`.

That does not necessarily mean that the issue is a _compatibility_ issue, but it is worth mentioning. 

Can you please be more specific regarding which "latest stable build" of the EOS plugin you are using? 

Would that be `v3.1.3`?

**Comment by kenofori** [comment] 2024-05-20 19:02
@paulhazen Thank you for your prompt reply, yes its 3.1.3 via UPM.
Any near future plans for adding support of that? 
Thanks

**Comment by paulhazen** [comment] 2024-05-24 22:10
> @paulhazen Thank you for your prompt reply, yes its 3.1.3 via UPM. Any near future plans for adding support of that? Thanks

I would hate to make a prediction about the timeline for Unity 6 Preview support. We do have expanding the set of supported versions of Unity as a task we are actively engaging with - but the priority has been and is likely to remain focused on guaranteeing support for versions that are newer than what we currently support, but not as new as the preview versions.

Consequently, I'm going to label this issue accordingly and close it - but feel free to re-open if after moving to a different version of Unity you are still having the same problem and add further discussion here if you'd like to discuss further. Thank you for reaching out to us!

**Closed by paulhazen** 2024-05-24 22:10 UTC
Labels: bug, wontfix, build, unresolved
