### ISSUE TITLE
eos_dependencies.androidlib and build.gradle

### ISSUE THREAD

**Issue by arthur740212** [PlayEveryWare/eos_plugin_for_unity#1027] opened 2024-11-27 01:13 UTC
> ![image](https://private-user-images.githubusercontent.com/17327131/389767677-6aafbbeb-ff14-485f-aa82-95c1e702c7db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NTExNjcsIm5iZiI6MTczMjY1MDg2NywicGF0aCI6Ii8xNzMyNzEzMS8zODk3Njc2NzctNmFhZmJiZWItZmYxNC00ODVmLWFhODItOTVjMWU3MDJjN2RiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDE5NTQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlMTNmMWQwYmZkYzk0MDVmNzNjODMzODcxNDBmNGU3ODEzMTMzMTUxOWRlNDgxYzQ1YTUwZTE3NDdmYmZiMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.C_dEuOytw7wTQpWPao3s5SZ7fQXLfcamUf-JTHH21MU) ![image](https://private-user-images.githubusercontent.com/17327131/389768703-e07ffec6-8235-4387-8155-516dfc0e3bd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NTExNjcsIm5iZiI6MTczMjY1MDg2NywicGF0aCI6Ii8xNzMyNzEzMS8zODk3Njg3MDMtZTA3ZmZlYzYtODIzNS00Mzg3LTgxNTUtNTE2ZGZjMGUzYmQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDE5NTQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1M2I3Y2IwNmYyNTUwMjY4ZDRmMjdmYTk4ZWZmZGNjN2U3NzZhM2YyZWY4MWE5NDlmZmUxNGFlYmIzMmMyMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hdWVQ4429NI0UKbtI1AcJMB3NxzT8jCJTASgJyf_ljk)
> 
> I manually copied these files into the project ,and modified the eos_loginprotocol_stcheme parameter

With this I get an error when building - did you include build.gradle, inside `eos_dependencies.androidlib`?

```
eos_dependencies.androidlib\build.gradle': 15: Unexpected input: '{' @ line 15, column 9. android {
```

_Originally posted by @joetaylor1987 in https://github.com/PlayEveryWare/eos_plugin_for_unity/issues/992#issuecomment-2501805506_

Created a new issue to track this ticket

**Comment by arthur740212** [comment] 2024-11-27 01:29
Hello, the images attached wasn't able to show up.
But based on the info provided, we have some guesses.

The `PreBuild` function for Android from the plugin should copy the `.aar` and `.androidlib` into the right directory during build.
The folders respectively are `[ProjectName]\Assets\Plugins\Android\aar\eos-sdk.aar` 
and `[ProjectName]\Assets\Plugins\Android\EOS\eos_dependencies.androidlib`
Therefore, if you are trying to manually copy the files, make sure the directories look like this.

> eos_dependencies.androidlib\build.gradle': 15: Unexpected input: '{' @ line 15, column 9. android {
This line looks interesting however because we weren't able to reproduce this syntax error from the `build.gradle` we provided,
Is the content copy pasted to a new file?
Note that `.androidlib` is a special extension for Unity, Unity will build its content into a plugin according the build.gradle.
And this should be separate from the main gradle file.

If you have a screenshot of your project hierarchy or other clues that shouldn't be exposed, you can send those to
`eos-support@playeveryware.com`.

**Comment by joetaylor1987** [comment] 2024-11-27 02:07
I found out from `AndroidBuilder.cs` that there are specific paths required - namely that the libraries etc are supposed to reside in a folder called `PlatformSpecificAssets~/`. Since we're using a modified version of the PlayEveryware plugin provided by Epic as an early mobile adopter and that is imported into our Packages/ folder, we were running into an issue where folders with the tilde (`~`) were being ignored by git, so **AndroidBuilder** wasn't able to do its prebuild step. It looks like there's a second path that can be used: `etc/PlatformSpecificAssets/`. So to satisfy Android builder, I've moved our PlatformSpecificAssets into etc/

Even so, the Unity build fails parsing `build.gradle` with the above error.

Could you point me to where an instance AndroidBuilder is created please?

**Comment by joetaylor1987** [comment] 2024-11-27 02:45
I suspect the error is because the build.gradle file isn't being patched with the correct entries for **APIVERSION**, **TARGETSDKVERSION** and **BUILDTOOLS**

**Comment by joetaylor1987** [comment] 2024-11-27 04:31
I can confirm that in our case, the AndroidBuilder isn't running its prebuild step. I haven't figured out why yet, as when I run a build locally, the prebuild step _does_ happen. The difference is that our build machine is a Windows server that is running `BuildPipeline.BuildPlayer` in batchmode, whereas my local machine is macOS, and I tested a build by just hitting `Build` in build settings.

**Comment by arthur740212** [comment] 2024-11-27 19:28
Here are some questions we have to clarify the settings.

First, which version of Unity were you using, and which version of gradle was that Unity version targeting?
This might be related to the gradle file issue.

Secondly, you were able to run prebuild locally but not able to prebuild from a server. Is that the correct situation?
And if so, did the whole build complete locally, or does it fail at gradle build?

Lastly, where is this `build.gradle` located?
There is a `build.gradle` for `.androidlib` and should inside of the directory.
And there might be another `[maingradle].gradle` (depending on the Unity version) for the project itself, that will likely be in `Assets/Plugin/Android`, this file is the one that is likely to have the **APIVERSION**, **TARGETSDKVERSION** and **BUILDTOOLS** you mentioned, and it is not part of the plugin and will be either created by Unity or the user writes their own.

**Comment by joetaylor1987** [comment] 2024-11-27 22:27
I've figured out the issue: `PlatformSpecificBuilder`'s callbackOrder should be `0`, not `1` as per the comment:

https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/d8f4c9ebbbd462e81bc29a64f4376b071f169fff/Assets/Plugins/Source/Editor/Build/PlatformSpecificBuilder.cs#L64-L69

Otherwise, we can't guarantee that the `PlatformSpecificBuilder`'s `OnPreprocessBuild` function is being called before `BuildRunner`'s `OnPreprocessBuild`, which has its callback order set to 1:

https://github.com/PlayEveryWare/eos_plugin_for_unity/blob/d8f4c9ebbbd462e81bc29a64f4376b071f169fff/Assets/Plugins/Source/Editor/Build/BuildRunner.cs#L32-L37

This meant that on our Windows build server, the `AndroidBuilder` hadn't been created and installed before `BuildRunner`'s `OnPreprocessBuild` was run

**Comment by paulhazen** [comment] 2024-12-03 16:51
Marking this issue as closed now that the fix is in `development` and will be part of our next release.

**Closed by paulhazen** 2024-12-03 16:51 UTC
