### ISSUE TITLE
EOSPluginEditorConfigEditor and EpicOnlineServicesConfigEditor windows start piling up over time

### ISSUE THREAD

**Issue by julcreutz** [PlayEveryWare/eos_plugin_for_unity#456] opened 2023-11-05 14:03 UTC
**Describe the bug**
Over time, multiple instances of the aforementioned editor window are being created and they are causing editor exceptions.

**To Reproduce**
1. Work inside Unity
2. Maximize the console window and un-maximize it
3. After some time, the errors start popping up

**Expected behavior**
Only one instance of either window is possible, without exceptions being caused.

**Screenshots**
<img width="684" alt="image" src="https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/24528976/4387cef3-95ed-4c19-a424-3cb26e831c38">

<img width="1168" alt="image" src="https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/24528976/4a3f9426-fa02-4e47-9503-d8fd14c5855a">

**Desktop (please complete the following information):**
 - OS: macOS ARM
 - Editor
 - Unity 2022.3.10f1
 - 2.3.3

**Comment by arthur740212** [comment] 2023-11-06 20:51
We weren't able to reproduce the problem on either v2.3.3 or the latest v3.0.2.
Was there extra steps needed to hit the issue? (Opening the config editors for instance)

**Comment by julcreutz** [comment] 2023-11-06 21:32
I myself haven't found an easy way to reproduce it. When I reset my Unity layout, it stops happening for a while, but then happens again. I don't even make use of any of the epic APIs as of right now, the plugin is just sitting in the project.
I don't open the config editors at all, nor are they opened in some tab. It's super weird.
I will try upgrading to 3.0.2 and see if the issue persists.

**Comment by paulhazen** [comment] 2023-11-10 00:17
> I myself haven't found an easy way to reproduce it. When I reset my Unity layout, it stops happening for a while, but then happens again. I don't even make use of any of the epic APIs as of right now, the plugin is just sitting in the project. I don't open the config editors at all, nor are they opened in some tab. It's super weird. I will try upgrading to 3.0.2 and see if the issue persists.

Did upgrading resolve the issue for you?

**Comment by julcreutz** [comment] 2023-11-10 00:24
> > I myself haven't found an easy way to reproduce it. When I reset my Unity layout, it stops happening for a while, but then happens again. I don't even make use of any of the epic APIs as of right now, the plugin is just sitting in the project. I don't open the config editors at all, nor are they opened in some tab. It's super weird. I will try upgrading to 3.0.2 and see if the issue persists.
> 
> Did upgrading resolve the issue for you?

It has indeed. But now I get exceptions at runtime saying Mac and Linux are in preview, which is a bit counterintuitive
since they worked fine before.

**Comment by arthur740212** [comment] 2023-11-10 01:52
Does Mac and Linux build crash on those exceptions, or was it just a log?
It could be that the logs are just there to indicate we're still working on it.

**Comment by julcreutz** [comment] 2023-11-10 13:39
> Does Mac and Linux build crash on those exceptions, or was it just a log? It could be that the logs are just there to indicate we're still working on it.

Indeed, it is just logs.

**Comment by julcreutz** [comment] 2023-11-10 15:53
Okay, I have to report that the bug was not fixed. I get the same exceptions with the editor windows now.

**Comment by arthur740212** [comment] 2023-11-10 21:53
I did some research in Unity forums, it seems that the common fix is to revert layout settings, have you tried that approach.

**Comment by julcreutz** [comment] 2023-11-10 22:01
> I did some research in Unity forums, it seems that the common fix is to revert layout settings, have you tried that approach.

Yep, I did browsed through all of the Unity forums to find a solution already, but none have worked.

**Comment by arthur740212** [comment] 2023-11-10 22:37
Does Reset Factory settings also not work? That is really bizarre.
Have you tried importing everything in a new project and running from there?

We weren't able to repo the problem on multiple versions and platforms.
Would you mind giving us more detailed steps to reproduce the anomaly?

**Comment by julcreutz** [comment] 2023-11-10 22:55
Nope, the reset functionality inside Unity still makes it creep up after a while.
I will try reinstalling Unity completely and report back if the issue is still present.
Thanks for the patience!

**Comment by arthur740212** [comment] 2023-11-20 23:05
Hi!
We found a similar error by accident, with a possibly unrelated step.
If we change the API compatibility level in the player settings, the exact error log will show up when we press play in the editor.
The log will always exist until we restart unity.

With this coincidence reminding us about the issue, we were wondering if reinstalling Unity fix your problem?

**Comment by julcreutz** [comment] 2023-11-20 23:32
It did not fix the issue :/

**Comment by arthur740212** [comment] 2023-11-22 18:44
I wonder if it is a Unity version problem or Mac thing.
We have a new version 3.0.3 if you'd like to try it out.
Thanks for the feedback.

**Comment by paulhazen** [comment] 2023-11-28 16:40
Hi @julcreutz. Were you able to resolve your problem by upgrading to the newest version of the plugin, or is this still causing problems for you?

**Comment by julcreutz** [comment] 2023-11-28 17:04
> Hi @julcreutz. Were you able to resolve your problem by upgrading to the newest version of the plugin, or is this still causing problems for you?

I have upgraded to the newest version, same issue still occurring unfortunately!

**Comment by paulhazen** [comment] 2023-11-30 18:22
> > Hi @julcreutz. Were you able to resolve your problem by upgrading to the newest version of the plugin, or is this still causing problems for you?
> 
> I have upgraded to the newest version, same issue still occurring unfortunately!

Bummer sauce. I'll look into it today, thanks for getting back to me :)

**Comment by arthur740212** [comment] 2023-12-01 20:08
As a sanity check, would you mind trying cloning the `stable` branch from this repo, and check whether the issue exists.
We want to rule out anything external that might cause the break.

**Comment by julcreutz** [comment] 2023-12-08 19:09
> As a sanity check, would you mind trying cloning the `stable` branch from this repo, and check whether the issue exists. We'd like to rule out anything external that might cause the break.

Tried that, causes the same issue as when I install it via UPM.

**Comment by paulhazen** [comment] 2023-12-19 18:28
@julcreutz We are in the process of refactoring how we utilize the `EditorWindow` class in the plugin. I believe those changes will fix this issue - but at this time I don't think we have an easy solution for you. We'll continue to keep this post (and you) updated on our progress.

**Comment by arthur740212** [comment] 2023-12-20 15:57
After some testing, the delay between receive and sending audio is pretty much consistent on PC.

The delay growing issue was found on Android when screen-locked, and when unlocking the screen the audio will be shortly interrupted then back to the normal delay.

We will get the fix for this up for PR and track the lag on Android as a separate task.

**Comment by julcreutz** [comment] 2023-12-20 16:11
> @julcreutz We are in the process of refactoring how we utilize the `EditorWindow` class in the plugin. I believe those changes will fix this issue - but at this time I don't think we have an easy solution for you. We'll continue to keep this post (and you) updated on our progress.

Thank you so much!

**Comment by julcreutz** [comment] 2023-12-20 16:12
> After some testing, the delay between receive and sending audio is pretty much consistent on PC.
> 
> The delay growing issue was found on Android when screen-locked, and when unlocking the screen the audio will be shortly interrupted then back to the normal delay.
> 
> We will get the fix for this up for PR and track the lag on Android as a separate task.

Wrong issue?

**Comment by paulhazen** [comment] 2024-01-02 17:13
@julcreutz I think you're correct. @arthur740212 can you confirm?

**Comment by paulhazen** [comment] 2024-01-03 02:46
@julcreutz I've just opened a PR that has a good chance of resolving this issue. Since I'm unable to reproduce the issue, it's hard for me to be certain, but there were some things changed in this PR that can definitely cause the problems you mention here.

**Comment by paulhazen** [comment] 2024-01-10 18:55
Resolved in `development` branch.

**Closed by paulhazen** 2024-01-10 18:55 UTC
Labels: bug, pending
