### ISSUE TITLE
Can't Retrieve Connect Interface on Android

### ISSUE THREAD

**Issue by kdserra** [PlayEveryWare/eos_plugin_for_unity#850] opened 2024-08-18 21:17 UTC
**Describe the bug**
I upgraded from PlayEveryWare EOS 3.2.0 to 3.3.1 which introduced a bug where the plugin is unable to retrieve the EOS Connect Interface on Android.  It works perfectly fine in the Windows 10 Editor.

I did not forget to place EOSManager in scene, and I sucessfully retrieve the Singleton instance, just not the Connect Interface.

See video of the issue:
https://www.youtube.com/watch?v=BO-KQQ59xeM

**To Reproduce**
(Only tested on physical device Pixel 4, Android 13)

1. Create new Unity 2023.20f1 Project, Template: 3D BiRP
2. Import tarball: com.playeveryware.eos-3.3.1
3. Import Sample: "Standard Pack: EOS Plugin for Unity Samples"
4. Go to File -> Build Settings -> Switch to Android platform
5. Go to: Edit -> Project Settings -> Player -> Select Android -> Set Minimum API Level to "Android 6.0 'Marshmallow' (API level 23)"

6. After Import - Add the following script:

Demo.cs
```csharp
using UnityEngine;
using PlayEveryWare.EpicOnlineServices;
using TMPro;

public class Demo: MonoBehaviour
{
    [SerializeField] private TMP_Text _tmpText;
    
    private void Start()
    {
        var eosInstance = EOSManager.Instance;
        var connectInterface = eosInstance.GetEOSConnectInterface();
        _tmpText.text = "Retrieved EOS Connect Interface: " + (connectInterface != null);
    }
}
```

7. Attach Demo script to GameObject in scene
8. Assign _tmpText reference in scene to TMP Text
9. Save Scene
10. Run in editor, should show "Retrieved EOS Connect Interface: True" - worked fine.
11. Build for Android with Mono Scripting Backend
12. Run app on device
13. Notice text says "Retrieve EOS Connect: False".

**Expected behavior**
I expect the app to successfully retrieve the Connect Interface.
In the demo the text should say "Retrieve EOS Connect: True" on Android device.

**Actual behavior**
The app fails to retrieve the Connect Interface.
In the demo the text says "Retrieve EOS Connect: False" on Android device.

**Screenshots**
![1-exception](https://github.com/user-attachments/assets/718732e0-7b86-4e44-bc10-95ed7b703c6c)
![2-connect-interface-null-conditional operator-shortcircuit](https://github.com/user-attachments/assets/6bfcc934-872d-4caf-90dd-f164cd796746)
![3-platform-interface-null](https://github.com/user-attachments/assets/d6bae6d7-d1e0-4e42-a9c1-0479e0776c9c)

**Smartphone:**
 - Device: Pixel 4
 - OS: Android 13
 - Unity Version: 2022.3.20f1
 - Plugin Version: 3.3.1

**Additional context**

I get two warnings when I build for Android (Might not be related to this bug report):

Warning 1:
![4-warning](https://github.com/user-attachments/assets/03d1fa26-8621-461d-b24b-83ff05ee5ad2)

```
Plugin 'Packages/com.playeveryware.eos/Runtime/Windows/x64/EOSSDK-Win64-Shipping.lib' is not supported on Android, please deselect it in Plugin Inspector
System.Linq.Enumerable/WhereEnumerableIterator`1<object>:MoveNext ()
Bee.BeeDriver.BeeDriver:WriteDataForBuildProgram (Bee.BeeDriver.InternalState,System.Threading.Tasks.TaskCompletionSource`1<int>)
Bee.BeeDriver.BeeDriver/<>c__DisplayClass0_0:<BuildAsync>g__WriteData|0 ()
Bee.BeeDriver.BeeDriver:BuildAsync (Bee.BeeDriver.BuildRequest,System.Threading.CancellationToken)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```

Warning 2:
![5-warning](https://github.com/user-attachments/assets/f6e97a6e-6fcd-410b-a707-7d1b1f0f3f56)

```
Plugin 'Packages/com.playeveryware.eos/Runtime/Windows/x86/EOSSDK-Win32-Shipping.lib' is not supported on Android, please deselect it in Plugin Inspector
System.Linq.Enumerable/WhereEnumerableIterator`1<object>:MoveNext ()
Bee.BeeDriver.BeeDriver:WriteDataForBuildProgram (Bee.BeeDriver.InternalState,System.Threading.Tasks.TaskCompletionSource`1<int>)
Bee.BeeDriver.BeeDriver/<>c__DisplayClass0_0:<BuildAsync>g__WriteData|0 ()
Bee.BeeDriver.BeeDriver:BuildAsync (Bee.BeeDriver.BuildRequest,System.Threading.CancellationToken)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```

**Comment by kdserra** [comment] 2024-08-19 01:54
I just performed the same test using PlayEveryWare EOS 3.2.1 and the issue does not occur; I am able to retrieve the Connect Interface successfully on this platform.

**Comment by paulhazen** [comment] 2024-08-19 18:12
Hi @kdserra Thank you for providing such a complete report of the issue! I appreciate the attention to detail. I will look into this and get back to you soon with an update based on what I find.

**Comment by paulhazen** [comment] 2024-08-20 22:47
Brief update @kdserra: I was able to reliably reproduce the bug you are experiencing. I created a new package based off of the `development` branch, from which we will be making our next release. Unfortunately, this exposed a flaw in our package creation process that needs to be rectified before I can address this problem. I'm working on that right now, and will keep you appraised.

**Comment by paulhazen** [comment] 2024-08-26 19:44
@kdserra While the exact nature of the issue is not entirely clear, we have tested the upcoming release for this scenario and can confirm that it resolves this issue. I will leave this issue open and unresolved until we have actually _made_ that release (at which point I will update and close this issue).

**Comment by paulhazen** [comment] 2024-09-02 17:58
Our latest release does not exhibit this issue (as mentioned in the previous comment). Therefore, I am marking this issue as closed.

**Closed by paulhazen** 2024-09-02 17:58 UTC
Labels: bug, tracked
