### ISSUE TITLE
P2P crash

### ISSUE THREAD

**Issue by manelmourelo** [PlayEveryWare/eos_plugin_for_unity#392] opened 2023-09-06 09:48 UTC
**Describe the bug**
There's something crashing when using P2P to connect 2 players.

**To Reproduce**
1. Connect 2 players with P2P
2. Wait until it crashes

**Desktop:**
 - OS: Windows x64
 - Both Edito and standalone build
 - Unity Version 2021.3.15f1
 - Plugin Version 2.3.3

**Additional context**
Hi, I'm using the version 2.3.3 of the plugin with Unity 2021.3.15f1. When using P2P the game crashes (without showing any errors in the log file), sometimes it takes a while and sometimes it crashes when the connection is made. It crashes both in build (if the build is for 32 bits it always crashes when the connection is made) and in the Unity editor (it crashes the entire editor). The crash is related to the networking because when I play without using online it never crashes and it seems to be on the epic side because when I use Steam for the P2P or when I use the basic Netcode transport to connect 2 players in a local network it doesn't crash. I use EOSConnect instead of EOSAuth because I'm using steam accounts and I don't want to have to link accounts. 
I've tried updating the EOSSDK to the latest version and that hasn't fixed anything. I've seen that in the logs it keeps login messages that it's trying to receive messages from the other player, but if i check the profiler the P2P calls are made in the main thread. I've tried adding logs to the receive and send messages functions and both seem to work properly so I don't know what to do to solve this.

**Comment by Raxnam** [comment] 2023-09-12 01:22
WE are currently looking into this issue, It seems to have a lot of similarities with a few other issues we have traced back to our memory management. We are currently working on fixing the manager as a whole.

**Comment by Raxnam** [comment] 2023-09-19 19:09
We have some idea as to what may be causing the issue, but cant replicate this behavior on our samples. Would you be able to share a few different crash dumps with is though eos-support@playeveryware.com so we can compare a few different crashes against each other?

**Comment by greatOmouse** [comment] 2023-09-25 20:12
I've been looking around for a solution to this same issue, but never saw this was opened. Has there been any ideas thrown around as to why this is happening? or if a different version of the editor kills this issue for the time being? was it related to memory management?

I get similar crash reports with no error message and editor crashes as well. In looking at the general issue with a friend they thought it may have to do with threading / thread safety. Epic says on it's website not to use await async etc. as all EOS calls need to be on the main thread, and the EOS manager in the samples does tick from update, but I was thinking maybe there could be something related to how the network manager hooks into it that could be related to the problem. I'm very new to netcode in general, but I'm currently removing all coroutines etc. related to anything on network and I'll add here if that changes anything. I can provide some logs and dmp files if that would help as well. Thanks!

**Comment by greatOmouse** [comment] 2023-09-25 23:41
Only thing indicating an error in the stack trace seems to be this:
ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFB91DC74A8)
0x00007FFB91DC74A8 (UnityPlayer) (function-name not available)

**Comment by greatOmouse** [comment] 2023-09-28 00:03
I also seem to have gotten a memory allocation error pertaining to the input system as well. I've never gotten this playing locally, only on P2P network.

----------------------------------------------------------
Could not allocate memory: System out of memory!
Trying to allocate: 18446744070557600280B with 16 alignment. MemoryLabel: TempOverflow
Allocation happened at: Line:108 in 
Memory overview

[ ALLOC_TEMP_TLS ] used: 32768B | peak: 0B | reserved: 7798784B 
[ ALLOC_DEFAULT ] used: 194343596B | peak: 0B | reserved: 231088128B 
[ ALLOC_TEMP_JOB_1_FRAME ] used: 0B | peak: 0B | reserved: 2097152B 
[ ALLOC_TEMP_JOB_2_FRAMES ] used: 0B | peak: 0B | reserved: 2097152B 
[ ALLOC_TEMP_JOB_4_FRAMES (JobTemp) ] used: 9225214B | peak: 0B | reserved: 14680064B 
[ ALLOC_TEMP_JOB_ASYNC (Background) ] used: 0B | peak: 0B | reserved: 23068672B 
[ ALLOC_GFX ] used: 5785056B | peak: 0B | reserved: 33558528B 
[ ALLOC_CACHEOBJECTS ] used: 49484776B | peak: 0B | reserved: 60825600B 
[ ALLOC_TYPETREE ] used: 23056B | peak: 0B | reserved: 4194304B 
Could not allocate memory: System out of memory!
Trying to allocate: 18446744070557600280B with 16 alignment. MemoryLabel: TempOverflow
Allocation happened at: Line:108 in 
Memory overview

[ ALLOC_TEMP_TLS ] used: 32768B | peak: 0B | reserved: 7798784B 
[ ALLOC_DEFAULT ] used: 194343596B | peak: 0B | reserved: 231088128B 
[ ALLOC_TEMP_JOB_1_FRAME ] used: 0B | peak: 0B | reserved: 2097152B 
[ ALLOC_TEMP_JOB_2_FRAMES ] used: 0B | peak: 0B | reserved: 2097152B 
[ ALLOC_TEMP_JOB_4_FRAMES (JobTemp) ] used: 9225214B | peak: 0B | reserved: 14680064B 
[ ALLOC_TEMP_JOB_ASYNC (Background) ] used: 0B | peak: 0B | reserved: 23068672B 
[ ALLOC_GFX ] used: 5785056B | peak: 0B | reserved: 33558528B 
[ ALLOC_CACHEOBJECTS ] used: 49484776B | peak: 0B | reserved: 60825600B 
[ ALLOC_TYPETREE ] used: 23056B | peak: 0B | reserved: 4194304B 
UnityEngine.InputSystem.PlayerInput:OnActionTriggered(CallbackContext)
System.Action`1:Invoke(T)
UnityEngine.InputSystem.Utilities.DelegateHelpers:InvokeCallbacksSafe(CallbackArray`1&, TValue, String, Object)
UnityEngine.InputSystem.InputActionState:CallActionListeners(Int32, InputActionMap, InputActionPhase, CallbackArray`1&, String)
UnityEngine.InputSystem.InputActionState:ChangePhaseOfActionInternal(Int32, TriggerState*, InputActionPhase, TriggerState&)
UnityEngine.InputSystem.InputActionState:ChangePhaseOfAction(InputActionPhase, TriggerState&, InputActionPhase)
UnityEngine.InputSystem.InputActionState:ProcessDefaultInteraction(TriggerState&, Int32)
UnityEngine.InputSystem.InputActionState:ProcessControlStateChange(Int32, Int32, Int32, Double, InputEventPtr)
UnityEngine.InputSystem.InputActionState:UnityEngine.InputSystem.LowLevel.IInputStateChangeMonitor.NotifyControlStateChanged(InputControl, Double, InputEventPtr, Int64)
UnityEngine.InputSystem.InputManager:FireStateChangeNotifications(Int32, Double, InputEvent*)
UnityEngine.InputSystem.InputManager:UpdateState(InputDevice, InputUpdateType, Void*, UInt32, UInt32, Double, InputEventPtr)
UnityEngine.InputSystem.InputManager:UpdateState(InputDevice, InputEvent*, InputUpdateType)
UnityEngine.InputSystem.InputManager:OnUpdate(InputUpdateType, InputEventBuffer&)
UnityEngine.InputSystem.LowLevel.<>c__DisplayClass7_0:<set_onUpdate>b__0(NativeInputUpdateType, NativeInputEventBuffer*)
UnityEngineInternal.Input.NativeInputSystem:NotifyUpdate(NativeInputUpdateType, IntPtr)

**Comment by paulhazen** [comment] 2023-09-28 19:40
> Trying to allocate: 18446744070557600280B with 16 alignment. MemoryLabel: TempOverflow

I don't understand what the problem is... does your device not have 18.45 exabytes of memory? /s

I think that this may be a different issue, as this is a memory allocation issue. While the problem that the OP is having is definitely related to memory, it does not appear to be an issue of allocation. Good to keep in mind though, thanks for the extra information! :)

**Comment by greatOmouse** [comment] 2023-09-28 20:07
Thanks for the response! I run my games on a computer that spans football fields and has the computational power that requires all the energy of the sun so I'm not really sure why it didn't work...

I don't know the source of the allocation error to be honest so I just threw it in there. I'm wasn't sure if that came from something related to the plugin, as I don't have any crazy functions happening on input (works generally for entire game runtime with no alloc err), but I do modify a network variable. I also definitely could be missing something that gets away. I'd love to potentially provide any information I can regarding this issue, if you need crash logs and .dmp files, 99% of my crash logs don't contain this alloc message.

**Comment by paulhazen** [comment] 2023-11-10 00:11
This issue closed by PR #458.

**Closed by paulhazen** 2023-11-10 00:11 UTC
Labels: bug, investigate

**Comment by greatOmouse** [comment] 2023-11-10 05:34
> This issue closed by PR #458.

Hey thank you so much! I was wondering if since it was just done I'd have to wait a little longer to see it in a release? or what the timeline on that would be like, just wondering, again thanks for improving, supporting, and supplying this great plugin.
