### ISSUE TITLE
Android: `log_level_config.json` not found. 

### ISSUE THREAD

**Issue by jollypunch** [PlayEveryWare/eos_plugin_for_unity#788] opened 2024-07-17 13:13 UTC
I'm seeing this error in Android build after updating to latest from `3.1.0`:

```csharp
Error Unity FileNotFoundException: Config file "jar:file:///data/app/~~GlkpSHNC1KZ_kWCHd5yOKw==/*package name*-6PIJZtVpcHpmNAccpkJn_Q==/base.apk!/assets/EOS/log_level_config.json" does not exist.
```

I see the file in `StreamingAssets/EOS`, and I'm not seeing the issue in editor and PC, PS5 builds. Not sure about other platforms.

Using Unity `2021.3.35`. Is there any special setup needed for the new config file on Android?

**Comment by arthur740212** [comment] 2024-07-17 18:31
Here are some steps to troubleshoot this.
First, regenerate a `log_level_config.json` with the in `Tool -> Log Level Configuration`
Then try unzipping the built apk and check if the `log_level_config.json` exists.

**Comment by paulhazen** [comment] 2024-07-17 18:32
Hi @jollypunch, thanks for reaching out! 

I suspect that this may be a bug with our latest release. I will look into this issue and will either have a hotfix release for tomorrow morning that resolves the issue and will try to provide you with a stop-gap solution. @arthur740212, @WispyMouse do y'all have any other thoughts or otherwise have mind me taking ownership of this issue to run with it?

**Comment by paomeng-game** [comment] 2024-07-18 03:42
Hey guys,I download and import eos plugin 3.30 version in release page, it seems works well in any other platform,  but in Android Build, in my game, doesn't work well.

**Comment by paomeng-game** [comment] 2024-07-18 10:31
> Here are some steps to troubleshoot this. First, regenerate a `log_level_config.json` with the in `Tool -> Log Level Configuration` Then try unzipping the built apk and check if the `log_level_config.json` exists.

Appreciated to your idea, while it still doesn't work on Android Build, and when I unpack the apk file, I found log_level_config.json in on EOS folder indeed, Ummm... In fact, It make me many days to deal with this error. It was EOS Auth Interface Login not effect at all that I notice this error with a development build in Unity, as I debug it in VS2019. I try to move the file in this respritory(not release into StreamingAssets in my project, but continue to get this problem, then I try your solution, as before...
![屏幕截图 2024-07-15 231623](https://github.com/user-attachments/assets/76292bbd-7adf-49c8-b8da-9c98b0f479f7)
I used to change EOSManager.cs as this and it works.
![Screenshot 2024-07-18 182934](https://github.com/user-attachments/assets/27efdb4a-e5d4-4902-8d25-78dea43a3fdc)

**Comment by arthur740212** [comment] 2024-07-18 20:20
We have identified the issue. 
In `Config.Read`, `File.Exist` does not work for android files and will always return false, which then always throws an exception and prevent anything else from happening.

**Comment by jollypunch** [comment] 2024-07-30 13:28
Thank you, any ETA on release for this fix?

**Comment by jollypunch** [comment] 2024-08-05 21:19
Was the fix included in 3.3.1? I updated but I'm still getting the same error message.

**Comment by Prabesh002** [comment] 2024-08-12 14:36
> Was the fix included in 3.3.1? I updated but I'm still getting the same error message.

Hello, I am encountering the same issue as well but except there is no 
![image](https://github.com/user-attachments/assets/5cd156a2-31c9-4e09-84f4-c7e0dde56c37)
log level config does not exists.
I am using 3.3.1

**Comment by paulhazen** [comment] 2024-08-14 20:15
Since this issue does not appear to have been successfully resolved, I am re-opening it and will follow up shortly.

**Comment by arthur740212** [comment] 2024-08-14 22:05
Hello, the fixes are in 3.3.1.
Users can regenerate a `log_level_config.json` with the window in Tool -> Log Level Configuration.

**Comment by theo-rapidfire** [comment] 2024-08-14 22:16
Did a bit of investigation: the fix is not included in the release.

Investigation notes below:
---

The first launch after updating from `3.2.1` gives this exception during startup:

```
NullReferenceException: Object reference not set to an instance of an object
PlayEveryWare.EpicOnlineServices.LogLevelUtility.get_LogLevelList () (at ./Library/PackageCache/com.playeveryware.eos@3883db1ade/Runtime/Core/Utility/LogLevelUtility.cs:51)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.InitializeLogLevels () (at ./Library/PackageCache/com.playeveryware.eos@3883db1ade/Runtime/Core/EOSManager.cs:775)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner, System.String configFileName) (at ./Library/PackageCache/com.playeveryware.eos@3883db1ade/Runtime/Core/EOSManager.cs:591)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner) (at ./Library/PackageCache/com.playeveryware.eos@3883db1ade/Runtime/Core/EOSManager.cs:556)
```

The entrypoint is a call to `EOSManager.Instance.Init(eos)`.

Subsequent launches gives this exception:

```
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <b11ba2a8fbf24f219f7cc98532a11304>:0)
PlayEveryWare.EpicOnlineServices.LogLevelUtility.get_LogLevelList () (at ./Library/PackageCache/com.playeveryware.eos@3883db1ade/Runtime/Core/Utility/LogLevelUtility.cs:51)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.InitializeLogLevels () (at ./Library/PackageCache/com.playeveryware.eos@3883db1ade/Runtime/Core/EOSManager.cs:775)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner, System.String configFileName) (at ./Library/PackageCache/com.playeveryware.eos@3883db1ade/Runtime/Core/EOSManager.cs:591)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner) (at ./Library/PackageCache/com.playeveryware.eos@3883db1ade/Runtime/Core/EOSManager.cs:556)
```

Debugging shows that the `LogCategoryStringArray` is out of sync with the `logLevelConfig.LogCategoryLevelPairs` list.

![image](https://github.com/user-attachments/assets/97aa07b9-50b4-436f-8950-c09b636e2f85)
![image](https://github.com/user-attachments/assets/ee06e1ed-f5a1-4d26-a35a-469e5751b514)

(an extra small bonus issue, doesn't feel important)
Opening the Log Level Configuration tool mentioned above spams import warnings while the `log_level_config` asset is selected.
![image](https://github.com/user-attachments/assets/45e6df98-aeb6-4e7f-b09e-0549fc8662ea)
```
[Worker0] Import Error Code:(4)
Message: Build asset version error: assets/streamingassets/eos/log_level_config.json in SourceAssetDB has modification time of '2024-08-14T21:03:51.7697475Z' while content on disk has modification time of '2024-08-14T21:03:52.1448363Z'

UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
```

After saving the default log states using the tool, the errors appear to have been resolved in the Editor, but it does not work in an Android build, where I get this exception:

```
Exception: FileNotFoundException: Config file "jar:file:///data/app/~~NI-PtCGRmOdYWrO8YW_GWA==/com.rapidfiregames.backpackbrawl-2G5m7idDwaHqoi8DZm-IEQ==/base.apk!/assets/EOS/log_level_config.json" does not exist.
PlayEveryWare.EpicOnlineServices.Config.Read () (at <00000000000000000000000000000000>:0)
PlayEveryWare.EpicOnlineServices.Config.Get[T] () (at <00000000000000000000000000000000>:0)
PlayEveryWare.EpicOnlineServices.LogLevelUtility.get_LogLevelList () (at <00000000000000000000000000000000>:0)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.InitializeLogLevels () (at <00000000000000000000000000000000>:0)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Init (PlayEveryWare.EpicOnlineServices.IEOSCoroutineOwner coroutineOwner, System.String configFileName) (at <00000000000000000000000000000000>:0)
```

Looking at the package content, the changes made in the pull request https://github.com/PlayEveryWare/eos_plugin_for_unity/pull/792/files has not been included in the release.

![image](https://github.com/user-attachments/assets/c97739ef-190a-4551-80e2-03bc4cb1d304)

This can also be confirmed by looking at the upm repo - the changes are not present: https://github.com/PlayEveryWare/eos_plugin_for_unity_upm/blob/3883db1ade572305d67299a13af84f664734328c/Runtime/Core/Config.cs#L281

**Comment by arthur740212** [comment] 2024-08-14 22:33
Thank you for digging into this.
There must be something missing here,
They will be included in the next release.

**Comment by jollypunch** [comment] 2024-08-16 07:50
Yeah I had to embed the package and manually add the code change, after that the issue is fixed.

**Closed** 2024-09-02 18:00 UTC
Labels: bug, build, tracked, plugin_issue
