### ISSUE TITLE
Unable to incorporate it in my project.

### ISSUE THREAD

**Issue by unityguyrockstar** [PlayEveryWare/eos_plugin_for_unity#489] opened 2023-12-09 13:46 UTC
Hi,
Thank you for such an awesome plugin.
I have been able to use it in the demo scenes provided.
But I am not able to use it in my project.
Can you please tell me which method I have to call to unlock my achievements?
Thank you.

**Comment by andrew-hirata-playeveryware** [comment] 2023-12-13 00:56
Hello @unityguyrockstar,


It depends on what kind of achievement you have that you want to unlock, if it's just an achievement where it unlocks after the player does something, you can use the `EOSAchievementManager.UnlockAchievementManually` to as inspiration or directly to unlock an achievement. If it is a stats based one, it should automatically update when the stat has been updated.

Besides the achievements, what else is stopping you from using it in your project?

**Comment by TakoMarie** [comment] 2023-12-13 16:58
Hi @andrew-hirata-playeveryware,
I am facing a similar problem with unlocking the achievements, but I realized that I need the user to connect to their Epic Games Account first for the overlay to work and for the achievements to unlock. Maybe this is why @unityguyrockstar is unable to use the plugin. 
Could you please give an example of how to properly use the Auth Interface to let players sign in to their Epic Games account directly from the game.
Something like when the player click on a button and it opens the Epic Games web page where it asks the user to connect and accept the permissions, just like in the samples.
Thank you so much.

**Comment by andrew-hirata-playeveryware** [comment] 2023-12-18 18:51
The UILoginMenu.cs file in the sample has code in it that can help you see how to login and get everything hooked up. You'll almost certainly need to modify it a bit to get it working in your own title.

**Comment by paulhazen** [comment] 2024-01-02 17:56
Hi @unityguyrockstar and @TakoMarie. Were you both ultimately able to implement the plugin into your unity project? 

I'm going to close this issue for the time being because we don't have any documented steps to reproduce the problem. 

If you're still having an issue and can document the steps you took to incorporate the plugin into your project, and what exactly seems to have gone wrong, please feel free to re-open the issue. If you need additional guidance, you might want to check out the discussions tab for the project, or read some of our [documentation](https://github.com/PlayEveryWare/eos_plugin_for_unity?tab=readme-ov-file#getting-started) in greater detail if you haven't done so already. We're always looking to improve our docs - so if they fall short of helping you use the plugin we definitely would like to know :)

**Closed by paulhazen** 2024-01-02 17:56 UTC
Labels: unresolved
