### ISSUE TITLE
"Use Unity App Version for ..." checkmark set to true causes IOException during build

### ISSUE THREAD

**Issue by PetrBodnar** [PlayEveryWare/eos_plugin_for_unity#680] opened 2024-05-17 12:55 UTC
**Describe the bug**
"Use Unity App Version for ..." checkmark set to true causes IOException during build if Product Version in EOS Configuration is not equal to Application.version

**To Reproduce**
1. Set "Use Unity App Version for ..."  to true
2. Set Product Version in EOS Configuration to something different than current Application.version
3. Build

**Expected behavior**
Build should finish without IOException

**Desktop (please complete the following information):**
 - OS: Windows x64
 - Editor
 - Unity Version 2021.3.14f1
 - Plugin Version 3.1.3

**Additional context**
If Product Version in EOS Configuration equals to current Application.version than exception doesn't occurs.
I checked - if I made AutoSetProductVersion synchronous (removed all async and awaits, use sync variants of Get and Write) - than exception doesn't occurs.
Looks like problem is in 
`await eosConfig.WriteAsync(true);`
in AutoSetProductVersion.

Full stacktrace:
```
IOException: Sharing violation on path C:\path\to\project\Assets\StreamingAssets\EOS\EpicOnlineServicesConfig.json
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0019e] in <d6232873609549b8a045fa15811a5bd3>:0 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options) [0x00000] in <d6232873609549b8a045fa15811a5bd3>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions)
  at System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize) [0x00055] in <d6232873609549b8a045fa15811a5bd3>:0 
  at System.IO.StreamReader..ctor (System.String path, System.Boolean detectEncodingFromByteOrderMarks) [0x00007] in <d6232873609549b8a045fa15811a5bd3>:0 
  at System.IO.StreamReader..ctor (System.String path) [0x00000] in <d6232873609549b8a045fa15811a5bd3>:0 
  at (wrapper remoting-invoke-with-check) System.IO.StreamReader..ctor(string)
  at PlayEveryWare.EpicOnlineServices.Config.Read () [0x0000d] in C:\path\to\project\Packages\com.playeveryware.eos\Runtime\Core\Config.cs:134 
  at PlayEveryWare.EpicOnlineServices.Config.Get[T] () [0x00005] in C:\path\to\project\Packages\com.playeveryware.eos\Runtime\Core\Config.cs:86 
  at PlayEveryWare.EpicOnlineServices.Build.EACUtility.ReplaceFileContentVars (System.String filepath, System.String buildExeName) [0x00014] in C:\path\to\project\Packages\com.playeveryware.eos\Editor\Utility\EACUtility.cs:368 
  at PlayEveryWare.EpicOnlineServices.Build.EACUtility.InstallEACFiles (UnityEditor.Build.Reporting.BuildReport report) [0x00159] in C:\path\to\project\Packages\com.playeveryware.eos\Editor\Utility\EACUtility.cs:327 
  at PlayEveryWare.EpicOnlineServices.Build.EACUtility.ConfigureEAC (UnityEditor.Build.Reporting.BuildReport report) [0x0000f] in C:\path\to\project\Packages\com.playeveryware.eos\Editor\Utility\EACUtility.cs:396 
  at PlayEveryWare.EpicOnlineServices.Build.PlatformSpecificBuilder.PostBuild (UnityEditor.Build.Reporting.BuildReport report) [0x00008] in C:\path\to\project\Packages\com.playeveryware.eos\Editor\Build\PlatformSpecificBuilder.cs:119 
  at PlayEveryWare.EpicOnlineServices.Build.WindowsBuilder.PostBuild (UnityEditor.Build.Reporting.BuildReport report) [0x00000] in C:\path\to\project\Packages\com.playeveryware.eos\Editor\Windows\WindowsBuilder.cs:77 
  at PlayEveryWare.EpicOnlineServices.Build.BuildRunner.OnPostprocessBuild (UnityEditor.Build.Reporting.BuildReport report) [0x00009] in C:\path\to\project\Packages\com.playeveryware.eos\Editor\Build\BuildRunner.cs:132 
  at UnityEditor.Build.BuildPipelineInterfaces+<>c__DisplayClass18_0.<OnBuildPostProcess>b__1 (UnityEditor.Build.IPostprocessBuildWithReport bpp) [0x00000] in <6a5b55f2e18b419e9faedac06ac6af94>:0 
  at UnityEditor.Build.BuildPipelineInterfaces.InvokeCallbackInterfacesPair[T1,T2] (System.Collections.Generic.List`1[T] oneInterfaces, System.Action`1[T] invocationOne, System.Collections.Generic.List`1[T] twoInterfaces, System.Action`1[T] invocationTwo, System.Boolean exitOnFailure) [0x000ff] in <6a5b55f2e18b419e9faedac06ac6af94>:0 
```

**Comment by paulhazen** [comment] 2024-05-24 22:06
Good catch - and narrow testing conditions but you certainly document them well. Once we get the next release out, I'll put this at the top of my list of things to fix - seems like low hanging fruit that we will be able to change with relative ease.

I apologize once again for the delay in our response. Am I reading-between the lines correctly that this is not an issue that currently blocks you. In other words - you've found a work-around, but more appropriately the change should be made in our codebase, so you don't have to maintain it. Am I reading things correctly?

**Comment by PetrBodnar** [comment] 2024-05-27 06:23
Yes, you are right!

**Comment by paulhazen** [comment] 2024-05-27 15:49
> Yes, you are right!

Excellent! In light of that, I'm going to mark this issue as "unresolved," and close it. It ought to be addressed in the next release which should be out within the next month - but hopefully sooner.

**Closed by paulhazen** 2024-05-27 15:49 UTC
Labels: bug, unresolved

**Comment by paulhazen** [comment] 2024-07-02 19:05
Removing the `unresolved` label as the issue is fixed in the upcoming release.
