### ISSUE TITLE
StartConnectLoginWithEpicAccount throw InvalidOperationException

### ISSUE THREAD

**Issue by ZhangHuan0407** [PlayEveryWare/eos_plugin_for_unity#766] opened 2024-07-04 02:50 UTC
**Describe the bug**
My game is plugged in, and after Epic was launched, some players triggered and uploaded this error. 
I didn't reproduce it on my own computer myself, but after a quick reading of the code, I suspected that there was something wrong with the code and needed help.

**Exception**
InvalidOperationException: Nullable object must have a value.
System.Nullable`1[T].get_Value () (at <00000000000000000000000000000000>:0)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.StartConnectLoginWithEpicAccount (Epic.OnlineServices.EpicAccountId epicAccountId, PlayEveryWare.EpicOnlineServices.EOSManager+OnConnectLoginCallback onConnectLoginCallback) (at <00000000000000000000000000000000>:0)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton+<>c__DisplayClass66_0.b__0 (Epic.OnlineServices.Auth.LoginCallbackInfo& data) (at <00000000000000000000000000000000>:0)
Epic.OnlineServices.Bindings.EOS_Platform_Tick (System.IntPtr handle) (at <00000000000000000000000000000000>:0)
PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Tick () (at <00000000000000000000000000000000>:0)

**How do I use the EOS plugin**
```
        EOSManager.Instance.StartPersistentLogin(LoginCallback);
        static void LoginCallback(Epic.OnlineServices.Auth.LoginCallbackInfo loginCallbackInfo)
        {
#if UNITY_EDITOR
            Debug.Log($"Epic EOS Login ResultCode: {loginCallbackInfo.ResultCode} {loginCallbackInfo.LocalUserId}");
#endif
            if (loginCallbackInfo.ResultCode == EOSResultCode.Success)
            {
                ConnectLoginEpicAccount(loginCallbackInfo.LocalUserId);
            }
            else
            {
                EOSManager.Instance.StartLoginWithLoginTypeAndToken(
                    Epic.OnlineServices.Auth.LoginCredentialType.AccountPortal,
                    Epic.OnlineServices.ExternalCredentialType.Epic,
                    null, null,
                    loginResult => ConnectLoginEpicAccount(loginResult.LocalUserId));
            }
        }
        // async callback after www request
        static void ConnectLoginEpicAccount(EpicAccountId localUserId)
        {
            EventDistributor.TriggerStopEpicLoginWaiting();
            EOSManager.Instance.StartConnectLoginWithEpicAccount(localUserId, (Epic.OnlineServices.Connect.LoginCallbackInfo connectLoginCallbackInfo) =>
            {
                if (connectLoginCallbackInfo.ResultCode == EOSResultCode.Success)
                {
                    LoginSuccess();
                }
                else if (connectLoginCallbackInfo.ResultCode == EOSResultCode.InvalidUser)
                {
                    // ask user if they want to connect; sample assumes they do
                    EOSManager.Instance.CreateConnectUserWithContinuanceToken(connectLoginCallbackInfo.ContinuanceToken, (Epic.OnlineServices.Connect.CreateUserCallbackInfo createUserCallbackInfo) =>
                    {
                        EOSManager.Instance.StartConnectLoginWithEpicAccount(localUserId, (Epic.OnlineServices.Connect.LoginCallbackInfo retryConnectLoginCallbackInfo) =>
                        {
                            if (retryConnectLoginCallbackInfo.ResultCode == EOSResultCode.Success)
                            {
                                LoginSuccess();
                            }
                        });
                    });
                }
            });
        }
```

**To Reproduce**
1. If player click "login epic account" button, I will invoke "EOSManager.Instance.StartPersistentLogin(LoginCallback);"
2. Some players triggered and uploaded error logs

**Expected behavior**
Errors should not be throw internally in EOS plugins

**Screenshots**
The player only reported the error log

**Desktop (please complete the following information):**
 - OS: Windows x64
 - standalone build
 - Unity Version 2021.3.33f1
 - Plugin Version com.playeveryware.eos-3.0.3
 - il2cpp √

**Additional context**
- Please open EOSManager.cs file.
- Nearly "public void StartConnectLoginWithEpicAccount" method.
```
// authToken is null or struct value
var result = EOSAuthInterface.CopyUserAuthToken(ref copyUserTokenOptions, epicAccountId, out Token? authToken);
...
// this condition made me realize that the authToken might be null
else if (authToken.HasValue && authToken.Value.RefreshToken != null)
{
    // this block have checked authToken is not null
    ...
    var result = EOSAuthInterface.CopyUserAuthToken(ref copyUserTokenOptions, callbackInfo.LocalUserId, out Token? userAuthToken);
    connectLoginOptions.Credentials = new Epic.OnlineServices.Connect.Credentials
    {
        // here!!! Use userAuthToken directly without checking for null
        Token = userAuthToken.Value.AccessToken,
        Type = ExternalCredentialType.Epic
    };
}
else
{
    connectLoginOptions.Credentials = new Epic.OnlineServices.Connect.Credentials
    {
        // here!!! Use authToken directly without checking for null
        Token = authToken.Value.AccessToken,
        Type = ExternalCredentialType.Epic
    };

    StartConnectLoginWithOptions(connectLoginOptions, onConnectLoginCallback);
}
```

- I tested locally when the nullable value type is null, and the null case is not checked
```
int? aa = null;
Debug.Log(aa.Value); // InvalidOperationException: Nullable object must have a value.
```

- The code that calls the EOS plugin is copied from the network and modified. 
- If it's a process error for me to call the plugin, please give the correct call flow in general.

Thank you very much for your help

**Comment by WispyMouse** [comment] 2024-07-04 21:21
Ahoy @ZhangHuan0407 ! Let's try and figure this out.

I think you're right, the issue is that the `authToken` is having its `Value` accessed while null. I'll be submitting a pull request to change this, and I'll get some replacement code for this function soon.

I'm surprised that the code is getting to the point of that nullable error, though. If the result from `EOSAuthInterface.CopyAuthToken` is `Result.NotFound`, it's supposed to stop there, and return `Result.ConnectAuthExpired` to the `onConnectLoginCallback`. If it isn't `Result.NotFound`, then what error is happening? Can you please share me the function you included in `Additional context`? I think that will help me with debugging your issue.

**Comment by ZhangHuan0407** [comment] 2024-07-05 03:07
This is my first time releasing a game on Epic, and this little game only uses Epic Login and Achievements.
Because the game is released for free, there is no anti-cracking method. Signing in to your Epic account need click a button. 
According to the error log location, this error occurs when the player clicks to log in.
Login is not mandatory, and the error here is equivalent to the player not clicking the login button...

Application.logMessageReceived += LogMessageRecieve;
When an exception occurs, a pop-up board will pop up telling the player to "click the button to send an error report".That's why I'm aware of this error.
The cumulative number of error reports divided by the cumulative number of players is approximately equal to 2%, I tried a few things, but it didn't reproduce the same error.

An Epic player could theoretically copy a folder to a friend who doesn't have an Epic account... 
What happens in this case I didn't test at all.

**Comment by ZhangHuan0407** [comment] 2024-07-05 03:14
I've already pasted the code to call EOSManager in “How do I use the EOS plugin”. (In the initial bug report)
LoginSuccess modifies the ui display status and invoke
EOSManager.Instance.GetEOSStatsInterface().IngestStat
There are no other EOSManager calls for the entire project

**Comment by ZhangHuan0407** [comment] 2024-07-05 03:35
2024-07-05T11:32:19.8989521+08:00 LogHttp(Warning): 000001B4BA103680: libcurl info message cache 1 (Closing connection 4)
2024-07-05T11:32:19.9030092+08:00 LogHttp(Warning): Retry exhausted on https://api.epicgames.dev/telemetry/data/datarouter/api/v1/public/data?SessionID=%7B250438F0-421B-F805-5278-689696836843%7D&AppID=EOSSDK.PhaseRelease.ReleaseBuild&AppVersion=1.16.0-27024038%20-%20%2B%2BEOSSDK%2BRelease-1.16-CL-27024038&UserID=&AppEnvironment=Production&UploadType=sdkevents
2024-07-05T11:32:20.2698988+08:00 LogHttp(Warning): 000001B4BA103680: invalid HTTP response code received. URL: https://api.epicgames.dev/sdk/v1/default?platformId=WIN, HTTP code: 0, content length: 0, actual payload size: 0
2024-07-05T11:32:20.2698988+08:00 LogHttp(Warning): 000001B4BA103680: request failed, libcurl error: 6 (Couldn't resolve host name)
2024-07-05T11:32:20.2698988+08:00 LogHttp(Warning): 000001B4BA103680: libcurl info message cache 0 (Could not resolve host: api.epicgames.dev)
2024-07-05T11:32:20.2698988+08:00 LogHttp(Warning): 000001B4BA103680: libcurl info message cache 1 (Closing connection 5)
2024-07-05T11:32:20.2698988+08:00 LogHttp(Warning): Retry exhausted on https://api.epicgames.dev/sdk/v1/default?platformId=WIN
2024-07-05T11:32:20.2698988+08:00 LogEOS(Warning): Failed to connect to the backend. ServiceName=[SDKConfig], OperationName=[GetPlatformConfigRoute], Url=[<Redacted>]
2024-07-05T11:32:20.2744923+08:00 LogEOS(Warning): SDK Config Platform Update Request Failed, Result Code: EOS_NoConnection, Retrying after 5.573168 seconds
2024-07-05T11:32:37.9323062+08:00 LogHttp(Warning): 000001B4BA103680: invalid HTTP response code received. URL: https://api.epicgames.dev/sdk/v1/default?platformId=WIN, HTTP code: 0, content length: 0, actual payload size: 0
2024-07-05T11:32:37.9323062+08:00 LogHttp(Warning): 000001B4BA103680: request failed, libcurl error: 6 (Couldn't resolve host name)
2024-07-05T11:32:37.9323062+08:00 LogHttp(Warning): 000001B4BA103680: libcurl info message cache 0 (Could not resolve host: api.epicgames.dev)
2024-07-05T11:32:37.9323062+08:00 LogHttp(Warning): 000001B4BA103680: libcurl info message cache 1 (Closing connection 6)
2024-07-05T11:32:37.9323062+08:00 LogHttp(Warning): Retry exhausted on https://api.epicgames.dev/sdk/v1/default?platformId=WIN
2024-07-05T11:32:37.9323062+08:00 LogEOS(Warning): Failed to connect to the backend. ServiceName=[SDKConfig], OperationName=[GetPlatformConfigRoute], Url=[<Redacted>]
2024-07-05T11:32:37.9363057+08:00 LogEOS(Warning): SDK Config Platform Update Request Failed, Result Code: EOS_NoConnection, Retrying after 14.881557 seconds
2024-07-05T11:32:37.9400583+08:00 LogEOSAuth(Warning): GenerateUserAuthByDeviceCode: Received FUserAuthError
2024-07-05T11:32:37.9450122+08:00 LogEOSAnalytics(Warning): Unable to get the client auth token. Last result: EOS_NoConnection.
2024-07-05T11:32:37.9506245+08:00 LogEOS(Error): EOS_Auth_CopyUserAuthToken - One or more parameters are null
PushDialog prefabPath: 1::UI/UploadDialog, GameObject: UploadDialog (UnityEngine.GameObject)
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
Game.UI.CameraCanvas:PushDialog(ResourceAddress)
Game.EventDistributor:LogMessageRecieve(String, String, LogType)
UnityEngine.Application:CallLogCallback(String, String, LogType, Boolean)

InvalidOperationException: Nullable object must have a value.
  at System.Nullable`1[T].get_Value () [0x00000] in <00000000000000000000000000000000>:0 
  at PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.StartConnectLoginWithEpicAccount (Epic.OnlineServices.EpicAccountId epicAccountId, PlayEveryWare.EpicOnlineServices.EOSManager+OnConnectLoginCallback onConnectLoginCallback) [0x00000] in <00000000000000000000000000000000>:0 
  at PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton+<>c__DisplayClass66_0.<StartLoginWithLoginOptions>b__0 (Epic.OnlineServices.Auth.LoginCallbackInfo& data) [0x00000] in <00000000000000000000000000000000>:0 
  at Epic.OnlineServices.Bindings.EOS_Platform_Tick (System.IntPtr handle) [0x00000] in <00000000000000000000000000000000>:0 
  at PlayEveryWare.EpicOnlineServices.EOSManager+EOSSingleton.Tick () [0x00000] in <00000000000000000000000000000000>:0

**Comment by ZhangHuan0407** [comment] 2024-07-05 03:46
Well, I now know what happened... 
There is a https://en.wikipedia.org/wiki/Great_Firewall in my region, So I have the vpn turned on when I am working, and I can't reproduce this error.
If you are accessing a foreign IP address, (I have test dev.epicgames.com, IP points to the United States) 
There is a chance that DNS resolution will fail, or TCP will be reset suddenly.
Generally speaking, players in my region will always have the VPN on to log in to Epic smoothly, but there may be some players who don't have the VPN on and have a connection error.  (result is EOS_NoConnection, parse token failed)

**Comment by WispyMouse** [comment] 2024-07-08 19:50
Seems like there's a few layers to this problem. Let's try to figure out the whole issue.

The first thing to look at is the login flow. For the Epic Online Services, you'll need to succeed at an Auth login, and then succeed at a Connect login. It looks like from some of the code you've shared that it might not be handling an error case. First, you call `StartPersistentLogin`. If the result code of that is not Success, you then use `EOSManager.Instance.StartLoginWithLoginTypeAndToken`, and provide `loginResult => ConnectLoginEpicAccount(loginResult.LocalUserId)` as the callback for a login. However, `ConnectLoginEpicAccount` isn't checking that the localUserId is actually populated, or that the `AccountPortal` login succeeded. Can you validate that the user has successfully done the `AccountPortal` login before trying to use the information for the Connect Login?

The second thing to look at is the error handling. Under Additional context you provided a snippet of code, which starts with an else if. I'm going to paste that code you shared to be clear about what I'm talking about:

```
// authToken is null or struct value
var result = EOSAuthInterface.CopyUserAuthToken(ref copyUserTokenOptions, epicAccountId, out Token? authToken);
...
// this condition made me realize that the authToken might be null
else if (authToken.HasValue && authToken.Value.RefreshToken != null)
{
    // this block have checked authToken is not null
    ...
    var result = EOSAuthInterface.CopyUserAuthToken(ref copyUserTokenOptions, callbackInfo.LocalUserId, out Token? userAuthToken);
    connectLoginOptions.Credentials = new Epic.OnlineServices.Connect.Credentials
    {
        // here!!! Use userAuthToken directly without checking for null
        Token = userAuthToken.Value.AccessToken,
        Type = ExternalCredentialType.Epic
    };
}
else
{
    connectLoginOptions.Credentials = new Epic.OnlineServices.Connect.Credentials
    {
        // here!!! Use authToken directly without checking for null
        Token = authToken.Value.AccessToken,
        Type = ExternalCredentialType.Epic
    };

    StartConnectLoginWithOptions(connectLoginOptions, onConnectLoginCallback);
}
```

I would like you to share the code for this function that is before the `else if (authToken.HasValue && authToken.Value.RefreshToken != null`.  Looking at the current stable branch, this statement is just an if without the else if, so I'm wondering if you have some changes on your side that we could look at. Either way, you've definitely found an error in the sample's authentication code with the nullable being used without checking if it has value, and I've committed something to try and fix it in to our development branch. I think from your issue here, my team should also add handling in case Result.NoConnection is the result code.

The third, reading this link, it appears as though the Epic Online Services does not have any servers inside of China.  https://eoshelp.epicgames.com/s/article/Does-Epic-Online-Services-operate-in-China-and-is-it-possible-to-configure-a-backend-region?language=en_US

> We do have relay servers across the world to enable efficient peer-to-peer network connectivity, however, Epic Online Services does not operate servers in mainland China.

This suggests that features for the Epic Online Services Plugin will not function for users who are accessing it from China, which is probably why you have a `NoConnection` result code from trying to use the plugin.

**Comment by ZhangHuan0407** [comment] 2024-07-09 03:27
The second question,
"else if" was modified in this submission
a74cb8b1ddbe887d3e8b8189b27b9f87d992d3f1

Sorry, I didn't notice that the source code for this method is not 100% the same for 3.03 and the main branch. I copied my local method
```

            //-------------------------------------------------------------------------
            /// <summary>
            /// 
            /// </summary>
            /// <param name="epicAccountId"></param>
            /// <param name="onConnectLoginCallback"></param>
            public void StartConnectLoginWithEpicAccount(Epic.OnlineServices.EpicAccountId epicAccountId, OnConnectLoginCallback onConnectLoginCallback)
            {
                var EOSAuthInterface = GetEOSPlatformInterface().GetAuthInterface();
                var copyUserTokenOptions = new Epic.OnlineServices.Auth.CopyUserAuthTokenOptions();
                var result = EOSAuthInterface.CopyUserAuthToken(ref copyUserTokenOptions, epicAccountId, out Token? authToken);
                var connectLoginOptions = new Epic.OnlineServices.Connect.LoginOptions();

                if (result == Result.NotFound)
                {
                    print("No User Auth tokens found to login");
                    if (onConnectLoginCallback != null)
                    {
                        var dummyLoginCallbackInfo = new Epic.OnlineServices.Connect.LoginCallbackInfo();
                        dummyLoginCallbackInfo.ResultCode = Result.ConnectAuthExpired;
                        onConnectLoginCallback(dummyLoginCallbackInfo);
                    }
                    return;
                }
                else if (authToken.HasValue && authToken.Value.RefreshToken != null)
                {
                    print("Attempting to use refresh token to login with connect");
                    // need to refresh the epicaccount id
                    // LoginCredentialType.RefreshToken
                    EOSManager.Instance.StartLoginWithLoginTypeAndToken(LoginCredentialType.RefreshToken, null, authToken.Value.RefreshToken, (callbackInfo) =>
                    {
                        var EOSAuthInterface = GetEOSPlatformInterface().GetAuthInterface();
                        var copyUserTokenOptions = new Epic.OnlineServices.Auth.CopyUserAuthTokenOptions();
                        var result = EOSAuthInterface.CopyUserAuthToken(ref copyUserTokenOptions, callbackInfo.LocalUserId, out Token? userAuthToken);

                        connectLoginOptions.Credentials = new Epic.OnlineServices.Connect.Credentials
                        {
                            Token = userAuthToken.Value.AccessToken,
                            Type = ExternalCredentialType.Epic
                        };

                        StartConnectLoginWithOptions(connectLoginOptions, onConnectLoginCallback);
                    });
                }
                else
                {
                    connectLoginOptions.Credentials = new Epic.OnlineServices.Connect.Credentials
                    {
                        Token = authToken.Value.AccessToken,
                        Type = ExternalCredentialType.Epic
                    };

                    StartConnectLoginWithOptions(connectLoginOptions, onConnectLoginCallback);
                }
            }
```

**Comment by ZhangHuan0407** [comment] 2024-07-09 04:59
The first question,
```
EOSManager.Instance.StartLoginWithLoginTypeAndToken
```
I quickly looked at the sample code and did do a diff based on the different return values.
For now, I'll only try to connect my epic account if the return value is EOSResultCode.Success.
Trying to reproduce the EOS_NoConnection situation again, it is indeed not a error.(The plugin uses version 3.03 and has no PR modifications)
Thank you very much for your help.

**Comment by WispyMouse** [comment] 2024-07-09 17:23
I'm glad I could help! I'm also glad you pointed out that the version of the code was different in a previous version; from now on when I try to answer these Issues, I'll ask about what version of the plugin is used.

Please close this issue if you feel like your problem is resolved, otherwise we can continue to assist!

**Closed** 2024-07-10 04:10 UTC
