### ISSUE TITLE
`NetworkManager.Singleton.DisconnectClient(id)` is disconnecting both the specified Client and the Host.

### ISSUE THREAD

**Issue by Ermelious** [PlayEveryWare/eos_plugin_for_unity#853] opened 2024-08-20 15:16 UTC
**Describe the bug**
NetworkManager.Singleton.DisconnectClient(id) is disconnecting both the specified Client and the Host.
Is there an example to Disconnect a specific client using this plugin because even in the Sameple scenes and sample scripts EOSLobbyManager, it behaves the same way where both the specified Client and Host disconnects.

EOSTransportManager only has Disconnect() which only works for Local Clients and not to Disconnect a remote client. When attempting to call  DisconnectClient directly from NetworkManager, the function does not work correctly/seems to have been overwritten by the plugin maybe? 

**To Reproduce**
1. Try calling NetworkManager.Singleton.DisconnectClient(id) with this plugin in the following scene:
Assets/Samples/Epic Online Services Plugin for Unity/3.3.0/Standard Pack _ EOS Plugin for Unity Samples/Scenes/Lobbies.unity (Create a fresh NetworkManager and add StartHost() and StartClient() respectively in CreateLobby() and JoinLobby() ins EOSLobbyManager.

**Expected behavior**
Should only Disconnect the specific ClientID and not the Host as well.

**Screenshots**
I think this issue is specific to PlayEveryWare as I've tested with the SamepleScenes as well, here's the error logs: https://discussions.unity.com/t/networkmanager-disconnectclient-is-causing-the-host-to-disconnect-as-well/1506402

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Editor
 - Unity Version: 6000
 - Plugin Version: Latest

**Additional context**

**Comment by paulhazen** [comment] 2024-08-20 18:01
> Alright so I've found that EOSTransport.DisconnectRemoteClient(ulong clientID) is the way to disconnect a client in this SDK not from NetworkManager.DisconnectClient(ulong clientID). I'm not sure why DisconnectClient(ulong clientID) does not work with this SDK and not sure if it is intended or not, but I will be using DisconnectRemoteClient since it gets the intended effect.
> 
> Should this still be classified as a bug?

Hi @Ermelious - glad you were able to find the right place to do that from! I will close this issue for the time being since it's not a bug, but it is worth tracking because you are not the first and probably will not be the last person to be confused by this. Thank you for providing your feedback - it's always valuable to have even if you end up finding a solution before we're able to get back to you :)

**Comment by paulhazen** [comment] 2024-08-29 18:04
I'm reopening this because the team has concluded that the resolution to this is not entirely complete. I will follow-up with details.

**Comment by Ermelious** [comment] 2024-08-29 20:38
> I'm reopening this because the team has concluded that the resolution to this is not entirely complete. I will follow-up with details.

Alright thanks for the update and anticipating a solution for this issue. Appreciate the assistance.

**Comment by Ermelious** [comment] 2024-09-03 19:06
Hi @paulhazen, may I check if you have any updates on this issue? How are current users of this plugin disconnecting the clients?

**Comment by paulhazen** [comment] 2024-09-10 17:49
Hi @Ermelious - I will look into this today and get you some answers - apologies for the delay.

**Comment by Ermelious** [comment] 2024-09-11 19:52
> Hi @Ermelious - I will look into this today and get you some answers - apologies for the delay.

Alright thank you. Hoping for a fix on this.

**Comment by paulhazen** [comment] 2024-09-13 17:59
> > Hi @Ermelious - I will look into this today and get you some answers - apologies for the delay.
> 
> Alright thank you. Hoping for a fix on this.

One aspect that may be affecting things is that you are utilizing Unity 6 in this particular case. It doesn't _immediately_ look like that is the source of the issue though - so I will continue to look into it and keep you appraised.

**Comment by Ermelious** [comment] 2024-09-13 18:57
> > > Hi @Ermelious - I will look into this today and get you some answers - apologies for the delay.
> > 
> > 
> > Alright thank you. Hoping for a fix on this.
> 
> One aspect that may be affecting things is that you are utilizing Unity 6 in this particular case. It doesn't _immediately_ look like that is the source of the issue though - so I will continue to look into it and keep you appraised.

That definitely doesn't seem to be the case since I've also checked with the Unity NGO discord community and their reps have stated that it is working on Unity 6. 

Are you implying that the function NetworkManager.Singleton.DisconnectClient(ClientID) is working on your end after following the reproduce steps I've included above? It is basically using the default scripts and scene in this plugin as seen in the steps.

**Comment by paulhazen** [comment] 2024-09-16 19:07
> > > > Hi @Ermelious - I will look into this today and get you some answers - apologies for the delay.
> > > 
> > > 
> > > Alright thank you. Hoping for a fix on this.
> > 
> > 
> > One aspect that may be affecting things is that you are utilizing Unity 6 in this particular case. It doesn't _immediately_ look like that is the source of the issue though - so I will continue to look into it and keep you appraised.
> 
> That doesn't seem to be the case since I've also checked with the Unity NGO discord community and their reps have stated that it is working on Unity 6, though they are using NGO and Unity's Lobby in this case. Not with this plugin. Hence our assumptions that there could be something in this plugin causing this behavior.
> 
> Are you implying that the function NetworkManager.Singleton.DisconnectClient(ClientID) is working on your end after following the reproduce steps I've included above? It is basically using the default scripts and scene in this plugin as seen in the steps.

No - it is failing per your repro steps. And you are correct that Unity 6 is not a factor. We are in the process of determining whether this should be expected behavior or not, considering how `DisconnectRemoteClient` provides expected behavior.

**Comment by Ermelious** [comment] 2024-09-17 17:54
> > > > > Hi @Ermelious - I will look into this today and get you some answers - apologies for the delay.
> > > > 
> > > > 
> > > > Alright thank you. Hoping for a fix on this.
> > > 
> > > 
> > > One aspect that may be affecting things is that you are utilizing Unity 6 in this particular case. It doesn't _immediately_ look like that is the source of the issue though - so I will continue to look into it and keep you appraised.
> > 
> > 
> > That doesn't seem to be the case since I've also checked with the Unity NGO discord community and their reps have stated that it is working on Unity 6, though they are using NGO and Unity's Lobby in this case. Not with this plugin. Hence our assumptions that there could be something in this plugin causing this behavior.
> > Are you implying that the function NetworkManager.Singleton.DisconnectClient(ClientID) is working on your end after following the reproduce steps I've included above? It is basically using the default scripts and scene in this plugin as seen in the steps.
> 
> No - it is failing per your repro steps. And you are correct that Unity 6 is not a factor. We are in the process of determining whether this should be expected behavior or not, considering how `DisconnectRemoteClient` provides expected behavior.

Alright, but if DisconnectRemoteClient is the expected behavior and to be used instead of DisconnectClient, than we will be going back once again to the requirement to expose the EOSTransport's ClientID which Andrew was stating it should not be used. 

Whichever way your team chooses, we just hope that there's a way on our side to Disconnect the client with a ClientID that matches both EOSTransport and NGO's client ID, this is critical since a lookup table to match the ClientID to ProductUserID is also required.

**Comment by paulhazen** [comment] 2024-09-18 18:35
> Interesting, but if DisconnectRemoteClient is the expected behavior and to be used instead of DisconnectClient, than we will be going back once again to the requirement to expose the EOSTransport's ClientID which Andrew was stating it should not be used.
> 
> Whichever way your team chooses, we just hope that there's a way on our side to Disconnect the client with a ClientID that matches both EOSTransport and NGO's client ID, this is critical since a lookup table to match the ClientID to ProductUserID is also required.

Yes - there was an element that I was not understanding when I wrote that response. The situation is a little more nuanced than I thought it was, so I will follow up with greater detail and a resolution to this. Apologies for the back-and-forth and delay.

**Comment by Ermelious** [comment] 2024-09-28 07:55
> > Interesting, but if DisconnectRemoteClient is the expected behavior and to be used instead of DisconnectClient, than we will be going back once again to the requirement to expose the EOSTransport's ClientID which Andrew was stating it should not be used.
> > Whichever way your team chooses, we just hope that there's a way on our side to Disconnect the client with a ClientID that matches both EOSTransport and NGO's client ID, this is critical since a lookup table to match the ClientID to ProductUserID is also required.
> 
> Yes - there was an element that I was not understanding when I wrote that response. The situation is a little more nuanced than I thought it was, so I will follow up with greater detail and a resolution to this. Apologies for the back-and-forth and delay.

Hi @paulhazen @andrew-hirata-playeveryware , can we check if there is a fix for this issue? Has been more than a month waiting for a fix for this issue. How are current users of this plugin disconnecting other clients when the functionality of this is broken?

**Comment by arthur740212** [comment] 2024-10-03 19:51
Hello, we have tracked this issue, the problem seems to be a bit more complicated than we expected.
The team will have a discussion about how we go about the solve, we will let you know when we get the fix out.
Thank you for your continued attention on the plugin.

**Comment by Ermelious** [comment] 2024-10-04 05:07
> Hello, we have tracked this issue, the problem seems to be a bit more complicated than we expected. The team will have a discussion about how we go about the solve, we will let you know when we get the fix out. Thank you for your continued attention on the plugin.

Thanks for the update!

**Comment by WispyMouse** [comment] 2024-11-13 21:21
Ahoy @Ermelious ! I wanted to reply to this to indicate this is being actively looked at, with high priority.

My current understanding of the situation is this: `NetworkManager` (the Unity code concept) has a `NetworkTransport` (abstract Unity class) that is implemented in `EOSTransport`. `NetworkManager` has a `ClientId` concept it internally manages, and `EOSTransport` has its own `ClientId` concept that it internally manages. You want to go from `ProductUserId` (EOS concept) to determining the `ClientId` of a target remote connection so that you can use it as a parameter in `DisconnectRemoteClient`. You've tried to address this by making the function for getting a Client Id that already exists inside `EOSTransport` to be public, but were told not to do that by our team because the value isn't necessarily directly related.

What I'm going to do next is to spend some time trying to determine the proper way for you to get the `ClientId`, and if the concepts are genuinely unrelated. It is my current understanding of the code, having only read it and not run it yet, that the `EOSTransport` actually provides the `ClientId` to `NetworkManager`; while they track this value separately, if your game only uses `EOSTransport` as its only transport class, then I *believe* that there's a 1:1 direct correct correlation between the ids... But I don't want to state that with confidence until I've done tests.

I'll get back to you by end of work day tomorrow with my results.

**Comment by WispyMouse** [comment] 2024-11-14 19:30
Ahoy @Ermelious ! I wanted to make sure I was replicating your set up, so I had a question. You outlined really well and clearly where to call `StartHost` and `StartClient`, but where are you calling `DisconnectClient`? Is it on the host's side, when the client wants to leave? Is it on the host's side, when the user is kicked?

**Comment by Ermelious** [comment] 2024-11-14 19:37
> Ahoy @Ermelious ! I wanted to make sure I was replicating your set up, so I had a question. You outlined really well and clearly where to call `StartHost` and `StartClient`, but where are you calling `DisconnectClient`? Is it on the host's side, when the client wants to leave? Is it on the host's side, when the user is kicked?

Ahoy @WispyMouse , it's particularly called on the Host, when the host wants to kick another connected Client / Player. Any luck? Just also wish to confirm, since I've been the only one reporting on this issue, is there actually a working way to do this? It's odd no other user of this plugin noticed this, considering it's quite an important feature, for the host to be able to kick others out.

**Comment by WispyMouse** [comment] 2024-11-14 19:51
Okay excellent, I'll put it on kick. Will get back to you soon.

> is there actually a working way to do this?

At the moment, in this project, there are no samples where a user is in a context that they're in a Lobby, using the Network Manager, and needs to be kicked. Our existing Lobby sample has the ability to kick people, but it doesn't use the NetworkManager. The netcode sample does use it, but doesn't have admin features like kicking exhibited. So it just hasn't come up before, and so no sample code was made to explicitly support this scenario.

You should be able to get everything you need to do this. I'm going to make sure to confirm the correct way for you to get this Id, and hopefully also discover why `DisconnectClient` is acting this erroneous way. By the end of this ticket we'll have answers for you on how to do this right, and I'll make sure that the repository is updated with the tools needed to do this. Thank you for your patience!

**Comment by WispyMouse** [comment] 2024-11-14 22:27
I want to make sure I have this set up the same way as you have. Here's what I've done;

- In `EOSLobbyManager.OnCreateLobbyCompleted`, the Host will run `NetworkManager.Singleton.StartHost`
- In `EOSLobbyManager.OnJoinLobbyCompleted`, the Client that is joining will set `EOSTransport.ServerUserIdToConnectTo` to the owner of the lobby, and then StartClient.
   - `(NetworkManager.Singleton.NetworkConfig.NetworkTransport as EOSTransport).ServerUserIdToConnectTo = CurrentLobby.LobbyOwner; NetworkManager.Singleton.StartClient();`
- I made `EOSTransport.GetClientId` public, as you have in a previous PR.
- Inside `UILobbiesMenu.KickButtonOnClick`, I add a callback that will disconnect a client.
```csharp
   - LobbyManager.KickMember(productUserId, (Result result) =>
            {
                ulong clientId = (NetworkManager.Singleton.NetworkConfig.NetworkTransport as EOSTransport).GetClientId(productUserId);

                Debug.LogError($"[MINT] [UILobbiesMenu] Kicking member from network. ProductUserId {productUserId} clientId {clientId}");

                NetworkManager.Singleton.DisconnectClient(clientId);
            });
```

From here, my reproduction steps are supposed to be like:

- Create three builds
- In build `HOSTBUILD`, start a Lobby that allows 3 members.
- In build `CLIENTBUILDONE`, join that Lobby.
- In build `CLIENTBUILDTWO`, join that Lobby.
- `HOSTBUILD` initiates a kick of `CLIENTBUILDONE`. This uses `KickButtonOnKick` which will eventually run the callback we provided to run `DisconnectClient`.

What I *expect* from your description above is that when `HOSTBUILD` kicks `CLIENTBUILDONE`, that something wrong will occur. I expect that from here, the `HOSTBUILD` will close its own host in addition to kicking the client.

Have I accurately outlined the situation and reproduction steps? Is there anything you'd like to add?

**Comment by WispyMouse** [comment] 2024-11-15 00:26
I've created a pull request that exposes the "GetClientId", but upon review of things it felt most appropriate to rename the function and add more comments. You're not getting the "client id", you're getting the "transport id"; a concept not named that directly, but it's present within look up tables and such. See the PR for more details.

We'll be having a new release of the plugin soon, and I'm not certain this change will make it in to the release. Either way, I think you're *safe* to make the EOSTransport.GetClientId function public and utilize it as you were, as long as you're passing that Id to EOSTransport and NOT NetworkManager.

I'm going to be out of office tomorrow, but we'll be back on Monday to help you out with this issue!

**Comment by Ermelious** [comment] 2024-11-15 02:08
> I've created a pull request that exposes the "GetClientId", but upon review of things it felt most appropriate to rename the function and add more comments. You're not getting the "client id", you're getting the "transport id"; a concept not named that directly, but it's present within look up tables and such. See the PR for more details.
> 
> We'll be having a new release of the plugin soon, and I'm not certain this change will make it in to the release. Either way, I think you're _safe_ to make the EOSTransport.GetClientId function public and utilize it as you were, as long as you're passing that Id to EOSTransport and NOT NetworkManager.
> 
> I'm going to be out of office tomorrow, but we'll be back on Monday to help you out with this issue!

That is exactly 100% the way I had implemented, and yes I had used EOSTransport.DisconnectRemoteClient(with the exposed "GetClientId") and not NetworkManager. But @andrew-hirata-playeveryware had stated it is not intended for use this way. So who's wrong here? @paulhazen excuse me for pinging that many members but due to how long it has been taking, I think there could be some confusion within the team on how to go about this fix?

Waited for months just to know that my original proposed fix here: https://github.com/PlayEveryWare/eos_plugin_for_unity/issues/853#issuecomment-2299266444
And
https://github.com/PlayEveryWare/eos_plugin_for_unity/issues/859#issuecomment-2307663402

Were actually the correct approach in this plugin?

**Comment by Ermelious** [comment] 2024-11-15 02:42
> I want to make sure I have this set up the same way as you have. Here's what I've done;
> 
> * In `EOSLobbyManager.OnCreateLobbyCompleted`, the Host will run `NetworkManager.Singleton.StartHost`
> * In `EOSLobbyManager.OnJoinLobbyCompleted`, the Client that is joining will set `EOSTransport.ServerUserIdToConnectTo` to the owner of the lobby, and then StartClient.
>   
>   * `(NetworkManager.Singleton.NetworkConfig.NetworkTransport as EOSTransport).ServerUserIdToConnectTo = CurrentLobby.LobbyOwner; NetworkManager.Singleton.StartClient();`
> * I made `EOSTransport.GetClientId` public, as you have in a previous PR.
> * Inside `UILobbiesMenu.KickButtonOnClick`, I add a callback that will disconnect a client.
> 
> ```cs
>    - LobbyManager.KickMember(productUserId, (Result result) =>
>             {
>                 ulong clientId = (NetworkManager.Singleton.NetworkConfig.NetworkTransport as EOSTransport).GetClientId(productUserId);
> 
>                 Debug.LogError($"[MINT] [UILobbiesMenu] Kicking member from network. ProductUserId {productUserId} clientId {clientId}");
> 
>                 NetworkManager.Singleton.DisconnectClient(clientId);
>             });
> ```
> 
> From here, my reproduction steps are supposed to be like:
> 
> * Create three builds
> * In build `HOSTBUILD`, start a Lobby that allows 3 members.
> * In build `CLIENTBUILDONE`, join that Lobby.
> * In build `CLIENTBUILDTWO`, join that Lobby.
> * `HOSTBUILD` initiates a kick of `CLIENTBUILDONE`. This uses `KickButtonOnKick` which will eventually run the callback we provided to run `DisconnectClient`.
> 
> What I _expect_ from your description above is that when `HOSTBUILD` kicks `CLIENTBUILDONE`, that something wrong will occur. I expect that from here, the `HOSTBUILD` will close its own host in addition to kicking the client.
> 
> Have I accurately outlined the situation and reproduction steps? Is there anything you'd like to add? One more question: are you running the Client from a standalone build, or the Editor? There's some behaviour differences in the Editor for StartClient.
> 
> Note
> 
> This is just trying to align with your repro steps; I don't yet advise making this method public. I will be spending time trying to determine if that's the correct thing to do; in the meantime I made it public to get to a repro. I haven't yet had the issue you've described to reproduce.

Not quite, the ClientID should be the one we get from NetworkManager.Singleton.ConnectedClients not EOSTransport to reproduce the issue, basically the original Unity way to disconnect the client without PlayEveryWare SDK. Paulhazen has also been able to reproduce the steps: https://github.com/PlayEveryWare/eos_plugin_for_unity/issues/853#issuecomment-2353704308

Additionally, your example above might be a "semi-fix" example, since you're using EOSTransport.GetClientID with NetworkManager.DisconnectClient (which are both referencing to different "ClientID", if you have clients leave the lobby once or twice until the Client has been assigned a different ClientID, it might present a different issue of attempting to disconnect an invalid client?

**Comment by WispyMouse** [comment] 2024-11-18 20:32
Ahoy! I'm sorry for the difficulties that have been involved here; you've essentially arrived at the correct destination. It took some significant amount of debugging and research, and deliberation with the team,, but in the end you were almost exactly correct in your original solution. I've had some code review and meetings with @andrew-hirata-playeveryware , in which he had agreed upon the perspective that this is the correct approach, as well as the language used in the comments of the function. The linked PR elaborates on this.

It took some time for our team to properly get the time and resources to put this through it's paces, and now we're confident that this solution aligns with how Unity and the plugin should work.

> Waited for months just to know that my original proposed fix here:
https://github.com/PlayEveryWare/eos_plugin_for_unity/issues/853#issuecomment-2299266444
And
https://github.com/PlayEveryWare/eos_plugin_for_unity/issues/859#issuecomment-2307663402
> 
> Were actually the correct approach in this plugin?

Yes, you're right. Your original fix was essentially correct.

> Additionally, your reproduction attempt example above might be a "semi-fix" example, since you're using EOSTransport.GetClientID with NetworkManager.DisconnectClient (which are both referencing 2 different "ClientID") [...]

Correct! The code I shared with you above while trying to comprehend your solution was incorrect; it was primarily to try and figure out how to reproduce things as you had it. You should indeed be using `EOSTransport.DisconnectRemoteClient` utilizing the id retrieved in `EOSTransport.GetTransportId`. The code sample I had above was before I had finished my investigation in to determining the correct solution, and was written before I understood the nuance between `EOSTransport.DisconnectClient` and `NetworkManager.DisconnectRemoteClient`.

> , if you have clients leave the lobby once or twice until the Client has been assigned a different ClientID, it might present a different issue of attempting to disconnect an invalid client?

*This* is why you can't use the Client Id where it wants Transport Id. You're correct in that if a user joins a session they might be assigned `1` as their ClientId and `1` as their TransportId; then they leave; then they return, and their `ClientId` will be `2` and their `TransportId` will still be `1`. As long as you consistently use the `TransportId` for `EOSTransport` and `ClientId` for `NetworkManager`, the Ids will correctly line up.

Again, I apologize for the long wait for this problem. Thank you for your patience.

**Comment by WispyMouse** [comment] 2024-12-02 19:34
Ahoy @Ermelious ! I wanted to check in on this Git Issue; are you unblocked and good to go? If so, I'd like to close this out.

**Comment by Ermelious** [comment] 2024-12-03 07:33
> Ahoy @Ermelious ! I wanted to check in on this Git Issue; are you unblocked and good to go? If so, I'd like to close this out.

@WispyMouse Am I correct to assume the fix is included in the latest version of the plugin since it's in the development branch? I've not tested it out and am still using my previous "work around" implementation to have the ability for the lobby leader to kick the player. I'll attempt at refactoring my code and implementing the official solution used in this plugin instead if it is ready. Feel free to close this issue if the fix is available, thanks!

**Comment by WispyMouse** [comment] 2024-12-04 19:22
> @WispyMouse Am I correct to assume the fix is included in the latest version of the plugin since it's in the development branch? 

Nope, it is not in the latest release! There is a long term project that's currently in `development`, but to fit the needs of our release schedule we needed to cherry-pick only exactly the C and C# SDK Integrations for the 1.16.4 EOS SDK drop. That will likely be true for the next release, as well, only containing essential code to the integration. While this set of code changes aren't likely to cause any issues, we're trying to be very careful given our situation.

I think you should continue using the code that you have. If you need to re-apply the samples for this project (EOSTransport.cs is part of the samples code), ensure that you reapply your custom code. This additional work won't be available in a release for at least a few weeks from now.

If you're comfortable doing so, you could fork this repository. The release branch was named `release-3.3.4`, and the tag is `v3.3.4`. Check out the associated branch or tag, and then you can cherry-pick the relevant changes into your project. That commit is here `https://github.com/PlayEveryWare/eos_plugin_for_unity/commit/b2cdf6f209433ff9fe15884aa0dcb6d28fcda8a9` and the sha is at the end of that, `b2cdf6f209433ff9fe15884aa0dcb6d28fcda8a9`. If you cherry-pick this change you'll have all of the associated work, which as a note is _only_ clarifying comments and renamed functions/variables.

Either way, thank you for your contributions to the plugin! If I have the power to do so, I'll letcha know when this gets integrated properly.

**Closed by WispyMouse** 2024-12-04 19:22 UTC
Labels: bug, tracked
