### ISSUE TITLE
EOSTransport ClientID does not match NGO ClientID

### ISSUE THREAD

**Issue by Ermelious** [PlayEveryWare/eos_plugin_for_unity#859] opened 2024-08-21 18:34 UTC
**Describe the bug**
Because EOSTransport ClientID does not match NGO ClientID especially the ones stored in the dictionary, calling some NGO functions such as NetworkManager.Singleton.ConnectedClients[clientId] does not work when using the EOSTransport ClientToUserID lookup dictionary to get the ID from the member's ProductUserID. This ClientID mismatches when the same Lobby Member re-enters the NGO server the 2nd time. 

**To Reproduce**
1. Set the following in any network script (Monitor the outcome when the same Lobby Member re-enters the Server multiple times. The ClientID in EOSTransport will no longer match the NGO NetworkClient's ID):
```c#
        NetworkManager.Singleton.OnConnectionEvent += (NetworkManager networkManager, ConnectionEventData connectionEventData) => 
        {
            bool isLocalClient = connectionEventData.ClientId == NetworkManager.Singleton.LocalClientId;
            NetworkManager.Singleton.ConnectedClients.ContainsKey(eosTransport.GetClientId(productUserId))
        };
```

**Expected behavior**
Is the following possible? The ClientID should match or use the NGO's ClientID instead of having EOSTransport generate its own ClientID.
This seems to be adding unnecessary complexity to build upon as both EOSTransport and NGO will have 2 separate ClientIDs. 
Though perhaps I've missed out the function in this SDK (perhaps there is an existing way to lookup ProductUserID to the NGO's ClientID? Kindly advice.

I've tried looking up EOSTransport and EOSTransportManager, can't seem to find a list where it stores all connections with their respective NGO NetworkClients that matches the ClientIDs and ProductUserIDs.

**Screenshots**
Just assumptions here, this is the portion of the EOSTransport.cs code that is assigning a separate client ID entirely disregarding the NGO Client ID. Is it possible to change it so that EOSTransport just takes the ClientID assigned by NGO or perhaps change NGO's client id so that it matches the one assigned by EOSTransport?
![image](https://github.com/user-attachments/assets/6de5fb28-de29-4ba6-a4e7-3f66da1223c8)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Editor
 - Unity Version: 6000
 - Plugin Version: Latest

**Comment by andrew-hirata-playeveryware** [comment] 2024-08-23 17:46
Hello @Ermelious 
It might be possible to unify the numbers, but fundamentally they're not the same concept.

To clarify things, in the EOSTransport, the client IDs in question are Transport Client IDs, not NetworkManager Client Ids. The naming convention where they're called 'client ids' is based on what the abstract classes are that one has to implement when providing a new transport.

If you look at the code for NetCode for Game Objects, the `NetworkManager` maintains a mapping between the more public Client Ids (The ones I'm calling NetworkManager Client IDs), and the internal client IDs that a given transport uses (The Transport Client IDs). So any API in NGO that requires a 'Client ID' is going to be referencing those client IDs, not the ones that the EOSTransport maintains.

This is also why the methods `GetClientId` and `GetUserId` are private. Having them be public would make it much easier for the APIs to be misused.

**Comment by andrew-hirata-playeveryware** [comment] 2024-08-29 18:10
Hello @Ermelious 

I think the root issue for this is that as you observed in in #853, there might be a bug in how `Disconnect` is implemented. We've reopened that and will continue looking into it there. 

For now, I'm going to close this issue as the root cause for the bug that you observed is that something is not working in `Disconnect`.

Thank you again for reporting the issue and continuing to collaborate as we work towards finding good solutions!

**Closed by andrew-hirata-playeveryware** 2024-08-29 18:10 UTC
Labels: tracked

**Comment by Ermelious** [comment] 2024-08-29 19:52
> Hello @Ermelious
> 
> I think the root issue for this is that as you observed in in #853, there might be a bug in how `Disconnect` is implemented. We've reopened that and will continue looking into it there.
> 
> For now, I'm going to close this issue as the root cause for the bug that you observed is that something is not working in `Disconnect`.
> 
> Thank you again for reporting the issue and continuing to collaborate as we work towards finding good solutions!

I see, so it was indeed a bug and we're not supposed to use DisconnectRemoteClient. Thanks for clearing that up. Yes in that case please ignore the changes to the public GetClientID and all other changes related to it in EOSTransport.

As it is an important feature that my project requires, hoping for a proper way to Disconnect a client in this plugin. Please do update if there's a function we could use when it is available. Thank you!
