### ISSUE TITLE
After the EOSManager is initialized, but before any other actions, "Failed to connect to Stomp! HS: ws upgrade unauthorized" error occurs regularly

### ISSUE THREAD

**Issue by BestStream** [PlayEveryWare/eos_plugin_for_unity#632] opened 2024-04-30 13:42 UTC

**Comment by arthur740212** [comment] 2024-04-30 19:37
Is `Stomp!` your game title?
EOSSDK doesn't contain something named like this as far as I know.
Could you provide more detail about your issue?

**Comment by BestStream** [comment] 2024-05-01 15:12
@arthur740212 I'm pretty sure this log is coming from your plugin or EOS. Look at the screenshot. I started working with the plugin a week ago and "Stomp" did not log errors. Before I submitted a bug, I received errors for 2 days. Today there are no errors again. It seems that this was a temporary issue on Epic's servers

![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/1887261/cbb43ac3-3241-4eea-8f8e-85a81f939052)

**Comment by BestStream** [comment] 2024-05-02 12:07
Yesterday and today again:
![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/1887261/0be84a56-e6e1-40e8-be5d-d917dd1d59b9)

**Comment by paulhazen** [comment] 2024-05-02 16:04
@arthur740212 "Stomp" _is_ actually a component of the EOS SDK. 

See [here](https://stomp.github.io/) for more information about what Stomp is.

@BestStream as for the issue you are experiencing, the best theory I have thus far is that the issue is Epic server related. This is based on the following observations:

- `HTTP 401` indicates an issue with the _task_ of authentication, not for circumstances where "unauthorized" access is attempted. So that tells us that it has to do with authentication. Since your values for authenticating have not changed, and the plugin has been working for the majority of users what's left is the reliability of Epic servers.
- The error is originating from within the EOS SDK layer of the plugin, not the plugin's implementation. Typically, that means that the issue is with certain configuration values that are found within the EOS developer portal pertaining to a specific product, sandbox, or deployment.

While researching this issue, it seems to be that others who experience it do so when there is a timeout or period of inactivity in the application. Can you lend greater context for us regarding when and where within the life cycle of your game this error presents itself?

Additionally, can you please provide the following information:
- What version of the plugin are you using?
- What platform are you targetting when you experience this bug?

**Comment by paulhazen** [comment] 2024-05-02 16:05
> Is `Stomp!` your game title? EOSSDK doesn't contain something named like this as far as I know. Could you provide more detail about your issue?

@arthur740212 "Stomp" _is_ actually a component of the EOS SDK. 

See [here](https://stomp.github.io/) for more information about what Stomp is.

**Comment by BestStream** [comment] 2024-05-02 17:36
@paulhazen 
As I mentioned, errors begin to occur after EOSManager is initialized and are repeated every few seconds.
Yesterday and this morning there were errors, but this evening they are gone.
Plugin 3.1.1
Unity 2022.3.13

**Comment by paulhazen** [comment] 2024-05-02 17:52
> @paulhazen As I mentioned, errors begin to occur after EOSManager is initialized and are repeated every few seconds. Yesterday and this morning there were errors, but this evening they are gone. Plugin 3.1.1 Unity 2022.3.13

Ah yes - I'm sorry. I forgot you included that in the title of the issue. 

Thanks for the additional information. 

I feel good about categorizing this as something that is an intermittent issue with Epic server availability and close the issue out, but if the problem returns, please come back and reopen the issue and we can look into it further. 

I've also marked the issue as `external` so we can track that and perhaps provide feedback to Epic directly.

**Closed by paulhazen** 2024-05-02 17:52 UTC
Labels: bug, wontfix, external
