### ISSUE TITLE
Lobby attributes not found on a device, working on others.

### ISSUE THREAD

**Issue by MenesApps** [PlayEveryWare/eos_plugin_for_unity#447] opened 2023-10-30 10:22 UTC
**Describe the bug**
I am having a weird issue : I have made a lobby system and it works fine on most devices but I have this Redmi A1 phone that I use for additional testing and it doesn't work there. The lobby made on the tablet appears in the list of available lobbies but its attributes are empty. I have checked on a third device (using the same build with the same lobby and at the same time) and the third device gets the attributes to populate the lobby UI and the phone doesn't. In the EOS console, the lobby can be found and its attributes are filled.
Anyone know why that would happen?

**To Reproduce**
Not sure. It simply doesn't get the lobby attributes on that one phone.

**Expected behavior**

I should get the attributes on all devices.

**Screenshots**
Device log that shows the empty attributes being returned.
![device log](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/13543160/35459ea7-442b-4818-a511-93652158a285)

Third device log that shows the attributes populated.
![Capture d’écran (100)](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/13543160/dfa7d031-793e-4026-b6b7-5ad5aa7cd2b9)

Code that handles the fetching of the lobby data.

```cs
foreach (KeyValuePair<Lobby, LobbyDetails> kvp in LobbyManager.GetSearchResults())
{
    if (kvp.Key == null)
    {
        Debug.LogError("Lobbies (OnSearchResultsReceived): SearchResults has null key!");
        continue;
    }

    if (kvp.Value == null)
    {
        Debug.LogError("Lobbies (OnSearchResultsReceived): SearchResults has null Value!");
        continue;
    }

    if (string.IsNullOrEmpty(kvp.Key.Id))
    {
        Debug.LogWarning("Lobbies (OnSearchResultsReceived): Found lobby with null Id: ");
        continue;
    }

    if (kvp.Key.LobbyOwner == null)
    {
        Debug.LogWarningFormat("Lobbies (OnSearchResultsReceived): Found lobby with null LobbyOwner id: ", kvp.Key.Id);
        continue;
    }
    string[] customizations;
    if (kvp.Key.LobbyOwner != null)
    {
        LobbyFound lobby = new LobbyFound();
        lobby.foundLobby = kvp.Key;
        lobby.foundLobbyDetails = kvp.Value;
        Epic.OnlineServices.Lobby.Attribute? outAttrbite;
        lobby.isVoice = true;
        //GameName
        var lobbyDetailsCopyAttributeByKeyOptions = new LobbyDetailsCopyAttributeByKeyOptions() { AttrKey = "gameAttribute" };
        Result attrResult = kvp.Value.CopyAttributeByKey(ref lobbyDetailsCopyAttributeByKeyOptions, out outAttrbite);
        if (attrResult == Result.Success)
        {
            lobby.language = outAttrbite?.Data?.Value.AsUtf8;
            Debug.Log("Language = " + lobby.language);
            //OwnerID
            lobbyDetailsCopyAttributeByKeyOptions = new LobbyDetailsCopyAttributeByKeyOptions() { AttrKey = "ownerID" };
            attrResult = kvp.Value.CopyAttributeByKey(ref lobbyDetailsCopyAttributeByKeyOptions, out outAttrbite);
            if (attrResult == Result.Success)
            {
                lobby.ownerID = outAttrbite?.Data?.Value.AsUtf8;
                Debug.Log("OwnerId = " + lobby.ownerID);
                //OwnerName
                lobbyDetailsCopyAttributeByKeyOptions = new LobbyDetailsCopyAttributeByKeyOptions() { AttrKey = "ownerName" };
                attrResult = kvp.Value.CopyAttributeByKey(ref lobbyDetailsCopyAttributeByKeyOptions, out outAttrbite);
                if (attrResult == Result.Success)
                {
                    lobby.ownerName = outAttrbite?.Data?.Value.AsUtf8;
                    Debug.Log("Owner name = "+ lobby.ownerName);
                    //Attribute1
                    lobbyDetailsCopyAttributeByKeyOptions = new LobbyDetailsCopyAttributeByKeyOptions() { AttrKey = "attribute1" };
                    attrResult = kvp.Value.CopyAttributeByKey(ref lobbyDetailsCopyAttributeByKeyOptions, out outAttrbite);
                    if (attrResult == Result.Success)
                    {
                        lobby.attribute1 = outAttrbite?.Data?.Value.AsUtf8;
                        Debug.Log("Attribute 1 = " + lobby.attribute1);
                        //Attribute2
                        lobbyDetailsCopyAttributeByKeyOptions = new LobbyDetailsCopyAttributeByKeyOptions() { AttrKey = "attribute2" };
                        attrResult = kvp.Value.CopyAttributeByKey(ref lobbyDetailsCopyAttributeByKeyOptions, out outAttrbite);
                        if (attrResult == Result.Success)
                        {
                            lobby.attribute2 = outAttrbite?.Data?.Value.AsUtf8;
                            Debug.Log("Attribute 2 = " + lobby.attribute2);
                            //Attribute3
                            lobbyDetailsCopyAttributeByKeyOptions = new LobbyDetailsCopyAttributeByKeyOptions() { AttrKey = "attribute3" };
                            attrResult = kvp.Value.CopyAttributeByKey(ref lobbyDetailsCopyAttributeByKeyOptions, out outAttrbite);
                            if (attrResult == Result.Success)
                            {
                                lobby.attribute3 = outAttrbite?.Data?.Value.AsUtf8;
                                Debug.Log("Attribute 3 = " + lobby.attribute3);
                                //Attribute4
                                lobbyDetailsCopyAttributeByKeyOptions = new LobbyDetailsCopyAttributeByKeyOptions() { AttrKey = "attribute4" };
                                attrResult = kvp.Value.CopyAttributeByKey(ref lobbyDetailsCopyAttributeByKeyOptions, out outAttrbite);
                                if (attrResult == Result.Success)
                                {
                                    lobby.attribute4 = outAttrbite?.Data?.Value.AsUtf8;
                                    Debug.Log("Attribute 4 = " + lobby.attribute4);
                                    //Attribute5
                                    lobbyDetailsCopyAttributeByKeyOptions = new LobbyDetailsCopyAttributeByKeyOptions() { AttrKey = "attribute5" };
                                    attrResult = kvp.Value.CopyAttributeByKey(ref lobbyDetailsCopyAttributeByKeyOptions, out outAttrbite);
                                    if (attrResult == Result.Success)
                                    {
                                        lobby.attribute5 = outAttrbite?.Data?.Value.AsUtf8;
                                        Debug.Log("Attribute 5 = " + lobby.attribute5);
                                        if (lobby.ownerID != v3AM.eosID) lobbies.Add(lobby);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
//All lobbies are there, now setup
if (GameObject.Find("Tavern")) GameObject.Find("Tavern").GetComponent<v3Tavern>().SetupResults();
```

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Editor 2021.3.26f1
 - Plugin Version 3.0.0

**Comment by paulhazen** [comment] 2023-10-30 22:14
There are a few things I would suggest as preliminary steps:

1. Double / Triple check that the version of your game is the same across all the devices. The issue you are describing sounds suspiciously like maybe an older build of the game is still lurking on the Redmi A1 device.
2. Try creating a lobby _from_ the Redmi A1 device, does it get propagated across the other devices properly, or do the other devices have a hard time seeing either the lobby or it's attributes?

**Comment by MenesApps** [comment] 2023-10-31 02:51
Hi, 
Thanks for the reply.
1. That's the first thing I thought too but I have uninstalled / reinstalled the app on the redmi several times. I don't think lingering data could still be on the phone but I can try to do a full reset of the device just to be sure.
2. I haved tried several times and it works fine when the lobby owner is the Redmi device. The Redmi can also find the lobby, it is just missing the attributes when trying to read them with LobbyDetailsCopyAttributeByKeyOptions(). The first check ` if (kvp.Key.LobbyOwner != null)` returns true so I am guessing the data is there, I just can't seem to access it (from the Redmi anyways).
Thanks for the help.

**Comment by MenesApps** [comment] 2023-10-31 08:59
Hi again,
So I tried to do a full reset of the phone. Built a new build for all devices and tried again. Same result I am afraid. Working on both tablet and editor, not working on the Redmi phone.

**Comment by paulhazen** [comment] 2023-11-01 18:18
@MenesApps This is all excellent additional information, thank you for the greater context! It is certainly strange behavior - and no immediate solution jumps to mind, but let's keep exploring.

In the original post, you mentioned that you are testing the lobby using three devices - one of them being the Redmi and the other being a tablet. Is the third device also a tablet, or is it a phone? Furthermore - regardless of form factor, are all the devices running exactly the same versions of Android? There is no obvious reason these differences should matter much, but I'm just trying to sus out what seems to be different about the Redmi from the other devices' behavior.

**Comment by MenesApps** [comment] 2023-11-02 10:51
The third device is also a phone (iPhone 11). Both the tablet and the Redmi are using Android 12, the iPhone uses iOS 16.7.2. I also use the Unity Editor (it works well there too).
I don't have other devices available but I can send you a link to the apk if you want to test on your end.

**Comment by paulhazen** [comment] 2023-11-02 21:06
It looks like this might be a known issue with the EOS SDK (version 1.16) itself: https://dev.epicgames.com/docs/epic-online-services/release-notes#lobbies-1

Is it possible that this is the issue you are running into?

The code listed there will not be directly relevant to you since it's a demonstration of a work-around when directly interacting with the EOS SDK. 

It _does_ however, indicate a possible solution - you would need to add or remove an arbitrary member attribute for the lobby owner whenever a lobby attribute is modified. 

I know this doesn't explain why the problem is noticed only on the Redmi, but it seemed similar enough that it was worth exploring. 

The APK would unfortunately not likely yield any additional information, except to confirm the behavior you've already reported, and I trust you on that already.

**Comment by MenesApps** [comment] 2023-11-03 09:29
I do not change the attributes or the lobby in general after creating it. But I noticed that when the lobby is created, ModifyLobby is called so I added this to the part where the attributes are applied to the lobby in this function. Like this : 
```cs
            // Add Lobby Attributes
            for (int attributeIndex = 0; attributeIndex < lobbyUpdates.Attributes.Count; attributeIndex++)
            {
                if (lobbyUpdates.Attributes[attributeIndex].Key != "LobbyAttributeChangeCounter")
                {
                    AttributeData attributeData = lobbyUpdates.Attributes[attributeIndex].AsAttribute;

                    LobbyModificationAddAttributeOptions addAttributeOptions = new LobbyModificationAddAttributeOptions();
                    addAttributeOptions.Attribute = attributeData;
                    addAttributeOptions.Visibility = lobbyUpdates.Attributes[attributeIndex].Visibility;

                    result = outLobbyModificationHandle.AddAttribute(ref addAttributeOptions);
                    if (result != Result.Success)
                    {
                        Debug.LogErrorFormat("Lobbies (ModifyLobby): Could not add attribute. Error code: {0}", result);
                        ModififyLobbyCompleted?.Invoke(result);
                        return;
                    }
                }
                else
                {
                    AttributeData attributeData = lobbyUpdates.Attributes[attributeIndex].AsAttribute;

                    LobbyModificationAddMemberAttributeOptions addAttributeOptions = new LobbyModificationAddMemberAttributeOptions();
                    addAttributeOptions.Attribute = attributeData;
                    addAttributeOptions.Visibility = lobbyUpdates.Attributes[attributeIndex].Visibility;

                    result = outLobbyModificationHandle.AddMemberAttribute(ref addAttributeOptions);
                    if (result != Result.Success)
                    {
                        Debug.LogErrorFormat("Lobbies (ModifyLobby): Could not add attribute. Error code: {0}", result);
                        ModififyLobbyCompleted?.Invoke(result);
                        return;
                    }
                    else
                    {
                        Debug.LogWarning("MemberAttribute fixed");
                    }
                }
            }
```
I also added the LobbyAttributeChangeCounter attribute to the original lobby creation function. 
I am absolutely not sure if this is what I was supposed to do, but since I don't modify the lobby myself, it is the only way I could think of. 

In any case, it sadly didn't work. A fresh build was made for both the tablet and the Redmi and same results. 

I also tried removing some attributes (in case I had too much somehow). It didn't help. I also tried to have additional attributes in the owner to see if the attributes were even taken into consideration. As expected, the Redmi wasn't able to fetch the incomplete lobby. So the attributes are there. 

A possible lead might be this warning when creating the lobby : `LogEOSLobby(Warning): Lobby backend has attributes missing from client` but according to this link [https://eoshelp.epicgames.com/s/question/0D54z00009c6AEzCAM/lobby-backend-has-attributes-missing-from-client-warning?language=en_US](url), this warning can be ignored.

Beyond that I am lost.

**Comment by MenesApps** [comment] 2023-11-06 12:58
Hi @paulhazen ,
I have tried to add a change to the lobby and put in the member update just in case and it didn't help. Do you have any other theory? Other than this issue, my game update is ready to be released.

**Comment by paulhazen** [comment] 2023-11-08 00:22
> I also added the LobbyAttributeChangeCounter attribute to the original lobby creation function.
I am absolutely not sure if this is what I was supposed to do, but since I don't modify the lobby myself, it is the only way I could think of.

So I think what is important is to update the attribute. To be clear - the attribute should be an attribute on the member that _owns_ the lobby, and the value for that attribute should be changed whenever a change is made to the lobby.

Referencing the suggestion I wrote earlier:

>It does however, indicate a possible solution - add, remove, or modify an arbitrary member attribute for the lobby owner whenever a lobby attribute is modified. You could accomplish this by adding a member attribute to the lobby owner like "LobbyAttributeChangeCounter," and incrementing it whenever an attribute on the lobby changes.

I'm realizing in retrospect that I may have made it unnecessarily complicated - it should be enough just to change the value of an arbitrary member attribute for the lobby owner whenever a lobby attribute is changed. I apologize if I may have not been clear enough.

Looking at the code you listed above, could you share the complete function code for additional context?

**Comment by MenesApps** [comment] 2023-11-08 15:33
I am not sure when to do the update then. I don't change the lobby once it is created. The flow is simple : the client A creates a lobby with the relevant attributes, the client B search a lobby and joins. When both players are in the same lobby, the game starts and the only interaction the players have with the lobby is through sending each other P2PNat messages until it is time to close the lobby.

Should I make an otherwise unneeded change to the lobby 

Here is the complete function (it is simply the ModifyLobby() from the EOSLobbyManager.cs from the sample with an addition for the member attribute I added to the lobby at creation).
```cs
public void ModifyLobby(Lobby lobbyUpdates, OnLobbyCallback ModififyLobbyCompleted)
        {
            // Validate current lobby
            if (!CurrentLobby.IsValid())
            {
                Debug.LogError("Lobbies (ModifyLobby): Current Lobby {0} is invalid!");
                ModififyLobbyCompleted?.Invoke(Result.InvalidState);
                return;
            }

            ProductUserId currentProductUserId = EOSManager.Instance.GetProductUserId();
            if (!currentProductUserId.IsValid())
            {
                Debug.LogError("Lobbies (ModifyLobby): Current player is invalid!");
                ModififyLobbyCompleted?.Invoke(Result.InvalidProductUserID);
                return;
            }

            if (!CurrentLobby.IsOwner(currentProductUserId))
            {
                Debug.LogError("Lobbies (ModifyLobby): Current player is not lobby owner!");
                ModififyLobbyCompleted?.Invoke(Result.LobbyNotOwner);
                return;
            }

            UpdateLobbyModificationOptions options = new UpdateLobbyModificationOptions();
            options.LobbyId = CurrentLobby.Id;
            options.LocalUserId = currentProductUserId;

            // Get LobbyModification object handle
            Result result = EOSManager.Instance.GetEOSLobbyInterface().UpdateLobbyModification(ref options, out LobbyModification outLobbyModificationHandle);

            if (result != Result.Success)
            {
                Debug.LogErrorFormat("Lobbies (ModifyLobby): Could not create lobby modification. Error code: {0}", result);
                ModififyLobbyCompleted?.Invoke(result);
                return;
            }

            // Bucket Id
            if (!string.Equals(lobbyUpdates.BucketId, CurrentLobby.BucketId))
            {
                var lobbyModificationSetBucketIdOptions = new LobbyModificationSetBucketIdOptions() { BucketId = lobbyUpdates.BucketId };
                result = outLobbyModificationHandle.SetBucketId(ref lobbyModificationSetBucketIdOptions);

                if (result != Result.Success)
                {
                    Debug.LogErrorFormat("Lobbies (ModifyLobby): Could not set bucket id. Error code: {0}", result);
                    ModififyLobbyCompleted?.Invoke(result);
                    return;
                }
            }

            // Max Players
            if (lobbyUpdates.MaxNumLobbyMembers > 0)
            {
                var lobbyModificationSetMaxMembersOptions = new LobbyModificationSetMaxMembersOptions() { MaxMembers = lobbyUpdates.MaxNumLobbyMembers };
                result = outLobbyModificationHandle.SetMaxMembers(ref lobbyModificationSetMaxMembersOptions);

                if (result != Result.Success)
                {
                    Debug.LogErrorFormat("Lobbies (ModifyLobby): Could not set max players. Error code: {0}", result);
                    ModififyLobbyCompleted?.Invoke(result);
                    return;
                }
            }
            
            // Add Lobby Attributes
            for (int attributeIndex = 0; attributeIndex < lobbyUpdates.Attributes.Count; attributeIndex++)
            {
                if (lobbyUpdates.Attributes[attributeIndex].Key != "LobbyAttributeChangeCounter")
                {
                    AttributeData attributeData = lobbyUpdates.Attributes[attributeIndex].AsAttribute;

                    LobbyModificationAddAttributeOptions addAttributeOptions = new LobbyModificationAddAttributeOptions();
                    addAttributeOptions.Attribute = attributeData;
                    addAttributeOptions.Visibility = lobbyUpdates.Attributes[attributeIndex].Visibility;

                    result = outLobbyModificationHandle.AddAttribute(ref addAttributeOptions);
                    if (result != Result.Success)
                    {
                        Debug.LogErrorFormat("Lobbies (ModifyLobby): Could not add attribute. Error code: {0}", result);
                        ModififyLobbyCompleted?.Invoke(result);
                        return;
                    }
                }
                else
                {
                    AttributeData attributeData = lobbyUpdates.Attributes[attributeIndex].AsAttribute;

                    LobbyModificationAddMemberAttributeOptions addAttributeOptions = new LobbyModificationAddMemberAttributeOptions();
                    addAttributeOptions.Attribute = attributeData;
                    addAttributeOptions.Visibility = lobbyUpdates.Attributes[attributeIndex].Visibility;

                    result = outLobbyModificationHandle.AddMemberAttribute(ref addAttributeOptions);
                    if (result != Result.Success)
                    {
                        Debug.LogErrorFormat("Lobbies (ModifyLobby): Could not add attribute. Error code: {0}", result);
                        ModififyLobbyCompleted?.Invoke(result);
                        return;
                    }
                    else
                    {
                        Debug.LogWarning("MemberAttribute fixed");
                    }
                }
            }

            // Permission
            if (lobbyUpdates.LobbyPermissionLevel != CurrentLobby.LobbyPermissionLevel)
            {
                var lobbyModificationSetPermissionLevelOptions = new LobbyModificationSetPermissionLevelOptions() { PermissionLevel = lobbyUpdates.LobbyPermissionLevel };
                result = outLobbyModificationHandle.SetPermissionLevel(ref lobbyModificationSetPermissionLevelOptions);

                if (result != Result.Success)
                {
                    Debug.LogErrorFormat("Lobbies (ModifyLobby): Could not set permission level. Error code: {0}", result);
                    ModififyLobbyCompleted?.Invoke(result);
                    return;
                }
            }

            // Allow Invites
            if (lobbyUpdates.AllowInvites != CurrentLobby.AllowInvites)
            {
                var lobbyModificationSetInvitesAllowedOptions = new LobbyModificationSetInvitesAllowedOptions() { InvitesAllowed = lobbyUpdates.AllowInvites };
                result = outLobbyModificationHandle.SetInvitesAllowed(ref lobbyModificationSetInvitesAllowedOptions);

                if (result != Result.Success)
                {
                    Debug.LogErrorFormat("Lobbies (ModifyLobby): Could not set allow invites. Error code: {0}", result);
                    ModififyLobbyCompleted?.Invoke(result);
                    return;
                }
            }


            //Trigger lobby update
            var updateLobbyOptions = new UpdateLobbyOptions() { LobbyModificationHandle = outLobbyModificationHandle };
            EOSManager.Instance.GetEOSLobbyInterface().UpdateLobby(ref updateLobbyOptions, ModififyLobbyCompleted, OnUpdateLobbyCallBack);
        }
```

**Comment by paulhazen** [comment] 2023-11-08 18:59
While I continue to explore other options - one solution that would enable you to launch the update would be to change your system requirements for the game to disallow Android Go from the supported options, assuming doing so is possible. It seems to be the only thing different about the Redmi device.

**Comment by MenesApps** [comment] 2023-11-08 19:16
I am adding a popup that will appear for players with this issue, letting them know they can still use the feature (since the missing attributes don't seem to affect the game itself, only the lobby screen) and ask them to send me a report. This way, I'll be able to make a list of the affected devices. Maybe this will help?

**Comment by paulhazen** [comment] 2023-11-08 19:53
> I am adding a popup that will appear for players with this issue, letting them know they can still use the feature (since the missing attributes don't seem to affect the game itself, only the lobby screen) and ask them to send me a report. This way, I'll be able to make a list of the affected devices. Maybe this will help?

This will definitely help! Additionally, I'll keep an eye here on this issue and be as responsive as I can in order to help you resolve things once there is more data on it. I'll continue looking into it in the meantime.

**Comment by MenesApps** [comment] 2023-11-09 08:41
Great. I'll post the update later this week and I'll come back here with the list.
Thanks

**Comment by MenesApps** [comment] 2023-11-22 08:07
Hi @paulhazen ,
So far, only 3 players are affected. The lobbies are working well for all the other players. Here are the info on their devices : 
-Model: samsung SM-A105FN / OS: Android OS 11 / API-30 (RP1A.200720.012/A105FNXXS9CWB1)
-Model: samsung SM-A136U1 / OS: Android OS 13 / API-33 (TP1A.220624.014/A136U1UEU5DWI5)
-Model: samsung SM-A137F / OS: Android OS 13 / API-33 (TP1A.220624.014/A137FXXS3CWI1).
Hope that helps.

**Comment by paulhazen** [comment] 2023-11-27 20:42
> Hi @paulhazen , So far, only 3 players are affected. The lobbies are working well for all the other players. Here are the info on their devices : -Model: samsung SM-A105FN / OS: Android OS 11 / API-30 (RP1A.200720.012/A105FNXXS9CWB1) -Model: samsung SM-A136U1 / OS: Android OS 13 / API-33 (TP1A.220624.014/A136U1UEU5DWI5) -Model: samsung SM-A137F / OS: Android OS 13 / API-33 (TP1A.220624.014/A137FXXS3CWI1). Hope that helps.

Looking at these devices I'm not seeming a common element of their OS that would suggest why this is happening.

> I am adding a popup that will appear for players with this issue, letting them know they can still use the feature (since the missing attributes don't seem to affect the game itself, only the lobby screen) and ask them to send me a report. This way, I'll be able to make a list of the affected devices. Maybe this will help?

Can you provide the code snippet that decides whether or not to display the pop-up to your users?

**Comment by MenesApps** [comment] 2023-12-01 10:17
Another device is "Model: samsung SM-T555 / OS: Android OS 7.1.1 / API-25 (NMF26X/T555XXU1CQJ5)". Besides my Redmi, all the other devices are Samsung. Thankfully, it appears to be affect few players.

The code is pretty simple actually : when I get the lobby search results (UIUpdateSearchResult), I check if the first returned attribute is empty or null. If it is I call the UrgentReport() function that sends the device info anonymously to me (and caches the warning in PlayerPrefs to prevent multiple reports from the same source)

```cs                
                var lobbyDetailsCopyAttributeByKeyOptions = new LobbyDetailsCopyAttributeByKeyOptions() { AttrKey = "gameAttribute" };
                Result attrResult = kvp.Value.CopyAttributeByKey(ref lobbyDetailsCopyAttributeByKeyOptions, out outAttribute);
                if (attrResult == Result.Success)
                {
                    if (outAttribute?.Data?.Value.AsUtf8 == "" || outAttribute?.Data?.Value.AsUtf8 == null)
                    {
                        if (!PlayerPrefs.HasKey("failedLobby"))
                        {
                            Debug.Log("FailedLobby");
                            UrgentReport();
                        }
                        else
                        {
                            Debug.Log("AlreadySent");
                        }
                    }
}`

**Comment by paulhazen** [comment] 2024-01-02 17:11
Because this issue affects so few of your users, and we're having such difficulty reproducing it, I'm going to close it for the time being. I'm sorry we weren't able to provide you with a better solution. I'm going to mark this issue so that we have a record of it not being fixed yet, so that as we build test scenarios we can add it and hopefully resolve it at that time. 

If something new regarding the problem occurs to you, you notice more users being affected, or you have additional input to provide please don't hesitate to re-open, or add your comments to the closed issue.

Thank you for your patience and extra information as we navigate this issue - and I'm sorry once again that we weren't able to find a more conclusive solution.

**Closed by paulhazen** 2024-01-02 17:11 UTC
