### ISSUE TITLE
EOS SDK Analytics disabled for route [1] — what does this mean?

### ISSUE THREAD

**Issue by 3ternal** [PlayEveryWare/eos_plugin_for_unity#388] opened 2023-09-01 22:16 UTC
**Describe the bug**
I'm getting the following warning when I boot up my game on Steam: EOS SDK Analytics disabled for route [1].

Full log:

```
Warning: 2023-09-01T18:02:40.9534823-04:00 LogEOSAnalytics(Warning): EOS SDK Analytics disabled for route [1].

UnityEngine.StackTraceUtility:ExtractStackTrace ()
ErrorHandler:GetFormattedLogMessage (string,string,UnityEngine.LogType)
ErrorHandler/<_ShowErrorMessage>d__23:MoveNext ()
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)
UnityEngine.MonoBehaviour:StartCoroutine (System.Collections.IEnumerator)
ErrorHandler:ReceiveLogMessageBuild (string,string,UnityEngine.LogType)
UnityEngine.Application:CallLogCallback (string,string,UnityEngine.LogType,bool)
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.LogOption,UnityEngine.Object,string,object[])
UnityEngine.Debug:LogFormat (UnityEngine.LogType,UnityEngine.LogOption,UnityEngine.Object,string,object[])
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:SimplePrintCallback (Epic.OnlineServices.Logging.LogMessage&)
Epic.OnlineServices.Logging.LoggingInterface:LogMessageFuncInternalImplementation (Epic.OnlineServices.Logging.LogMessageInternal&)
Epic.OnlineServices.Platform.PlatformInterface:Tick ()
PlayEveryWare.EpicOnlineServices.EOSManager/EOSSingleton:Tick ()
PlayEveryWare.EpicOnlineServices.EOSManager:Update ()
```

**Desktop (please complete the following information):**
 - OS: Win 10
 - Standalone build
 - Unity Version 2022.3.6
 - Plugin Version 2.3.3 (from OpenUPM)

**Additional context**
I'm not actually trying to use analytics in my game — I just needs achievements, stats, and rich presence. However, I didn't see any settings under Tools -> EpicOnlineServicesConfigEditor about enabling or disabling analytics.
Furthermore, I suppose this is "just" a warning, not an error, but I would rather not ignore it unless I know what it is.

**Comment by paulhazen** [comment] 2023-09-01 22:32
You are correct that it is a warning - and you are wise to not ignore it. For context - the warning actually originates from the EOS SDK itself and is bubbled up by the plugin. I believe it means that the analytics between the SDK and Epic Online Services has been disabled. I'll look into it more closely though to confirm - although I'm 80% certain this is the case.

**Comment by paulhazen** [comment] 2023-09-05 19:37
@3ternal I have confirmed that this is the case - more specifically - during development circumstances - the analytics for the EOS SDK are disabled (which makes sense, because I'm guessing Epic doesn't want to log development noise as regular SDK usage). 

Let me know if you have additional concerns - and also let me know if you don't - so I can close this issue if it indeed ought to be closed :) Also, thanks for filing an issue - open-source projects depend on folk doing that, so keep it up! :D

**Comment by 3ternal** [comment] 2023-09-05 19:42
Hey, thanks for looking into it. In conclusion, this means it's fine to just ignore the warning, correct? If so, we can go ahead and close the issue.

**Comment by paulhazen** [comment] 2023-09-05 20:07
> 

Yes that is correct. Closing issue :)

**Closed by paulhazen** 2023-09-05 20:07 UTC
