### ISSUE TITLE
Leaderboard Sample - Can't see leaderboard results

### ISSUE THREAD

**Issue by 3ternal** [PlayEveryWare/eos_plugin_for_unity#405] opened 2023-09-21 15:46 UTC
I'm having trouble with the Leaderboard scene in the Sample package. I can log in via PersistentAuth and see my list of leaderboards on the left. If I type in a number and click Ingest Stat, the console prints Ingest Stats Complete from line 486 of EOSLeaderboardManager.cs.

But, I can't actually see the result in the leaderboard, even after clicking Refresh. Same problem with my real project: the callback returns success, but on the EGS website, it shows no entries.

I'm unsure if this is a problem with the plugin or with my EGS configuration, but since it isn't working in the Sample, I thought I'd ask here. My leaderboards are still in Dev rather than Stage, for what it's worth. Also, the achievements appear to be working in both the sample and my full game - it's just stats/leaderboards that are giving trouble.

Unity 2022.3.6 / EOS Plugin 2.3.3 (the latest ver had an error, so I'm still on 2.3.3)

**Comment by paulhazen** [comment] 2023-09-21 21:08
We have noticed that the leaderboards are not always refreshed right away. I imagine that on Epic's side of things they recognize there is less urgency around keeping leaderboards accurate to the minute (don't quote me on that, but it's a guess). I can say that we have noticed leaderboards do not get updated right away. 

With that in mind, can you confirm that the leaderboards have _still_ not been updated to reflect what you had expected them to reflect? If by this point they do, it might just be an issue of delay.

**Comment by 3ternal** [comment] 2023-09-22 13:39
Hmm, good to know.

I just tested again, though, and the leaderboards still show no entries (both in the Unity editor and on the Epic website).

**Comment by paulhazen** [comment] 2023-09-25 22:32
> Hmm, good to know.
> 
> I just tested again, though, and the leaderboards still show no entries (both in the Unity editor and on the Epic website).

I am assuming you are still experiencing this error. When you use the sample scene for the Leaderboards, what does the log window display?

**Comment by 3ternal** [comment] 2023-09-26 13:44
I've copied the log:

```
13:41:51.640 [Log] : EOSManager: Registering for platform-specific notifications
<color=#FFFF00>13:41:51.640 [Warning] : EOSManager::Init: InitializePlatformInterface: initResult = AlreadyConfigured</color>
13:41:52.113 [Log] : EOSManager: Registering for platform-specific notifications
<color=#FFFF00>13:41:52.127 [Warning] : EOSManager::Init: InitializePlatformInterface: initResult = Success</color>
<color=#FFFF00>13:41:52.128 [Warning] : 2023-09-26T09:41:52.1283553-04:00 LogEOSAuth(Warning): FAccountPortalBrowserManager::Init: Failed to register overlay: EOS_NotConfigured</color>
<color=#FFFF00>13:41:52.922 [Warning] : 2023-09-26T09:41:52.9221775-04:00 LogEOSAnalytics(Warning): EOS SDK Analytics disabled for route [1].</color>
13:41:57.265 [Log] : Attempting to login...
13:41:57.812 [Log] : UserData (OnQueryUserInfoCompleted): QueryUserInfo successful
13:41:57.913 [Log] : Connect Login Successful. [Success]
13:41:57.988 [Log] : Leaderboard (LeaderboardDefinitionsReceivedCallbackFn): Query Definitions Complete
13:41:57.994 [Log] : Friends (QueryFriendsCallback): Query Friends Complete for user id: 85039fd444ff40e5aa6d8664fe8fce52
13:41:57.994 [Log] : Friends (QueryFriendsCallback): Number of friends: 0
13:41:58.001 [Log] : UserData (OnQueryUserInfoCompleted): QueryUserInfo successful
13:42:01.380 [Log] : Leaderboard (LeaderboardRanksReceivedCallbackFn): Query Ranks Complete
13:42:01.380 [Log] : Display Leaderboard Records: Count=0
13:42:09.447 [Log] : Leaderboard (StatsIngestCallbackFn): Ingest Stats Complete
13:42:11.287 [Log] : Leaderboard (LeaderboardDefinitionsReceivedCallbackFn): Query Definitions Complete```

I tried checking both Global and Friends, but the leaderboard remains blank.

**Comment by paulhazen** [comment] 2023-09-26 18:43
> I've copied the log:
> 
> ```
> 13:41:51.640 [Log] : EOSManager: Registering for platform-specific notifications
> <color=#FFFF00>13:41:51.640 [Warning] : EOSManager::Init: InitializePlatformInterface: initResult = AlreadyConfigured</color>
> 13:41:52.113 [Log] : EOSManager: Registering for platform-specific notifications
> <color=#FFFF00>13:41:52.127 [Warning] : EOSManager::Init: InitializePlatformInterface: initResult = Success</color>
> <color=#FFFF00>13:41:52.128 [Warning] : 2023-09-26T09:41:52.1283553-04:00 LogEOSAuth(Warning): FAccountPortalBrowserManager::Init: Failed to register overlay: EOS_NotConfigured</color>
> <color=#FFFF00>13:41:52.922 [Warning] : 2023-09-26T09:41:52.9221775-04:00 LogEOSAnalytics(Warning): EOS SDK Analytics disabled for route [1].</color>
> 13:41:57.265 [Log] : Attempting to login...
> 13:41:57.812 [Log] : UserData (OnQueryUserInfoCompleted): QueryUserInfo successful
> 13:41:57.913 [Log] : Connect Login Successful. [Success]
> 13:41:57.988 [Log] : Leaderboard (LeaderboardDefinitionsReceivedCallbackFn): Query Definitions Complete
> 13:41:57.994 [Log] : Friends (QueryFriendsCallback): Query Friends Complete for user id: 85039fd444ff40e5aa6d8664fe8fce52
> 13:41:57.994 [Log] : Friends (QueryFriendsCallback): Number of friends: 0
> 13:41:58.001 [Log] : UserData (OnQueryUserInfoCompleted): QueryUserInfo successful
> 13:42:01.380 [Log] : Leaderboard (LeaderboardRanksReceivedCallbackFn): Query Ranks Complete
> 13:42:01.380 [Log] : Display Leaderboard Records: Count=0
> 13:42:09.447 [Log] : Leaderboard (StatsIngestCallbackFn): Ingest Stats Complete
> 13:42:11.287 [Log] : Leaderboard (LeaderboardDefinitionsReceivedCallbackFn): Query Definitions Complete
> ```
> 
> I tried checking both Global and Friends, but the leaderboard remains blank.

Just to be clear - these are the log statements for when you try and query the leaderboard, or when you try and ingest a stat, or both? Looks like both but I wanted to confirm.

**Comment by 3ternal** [comment] 2023-09-26 18:58
Yeah, it's both. I guess I can record it just to be clear: https://streamable.com/gwe193

This time the log is a bit longer because I clicked around more.

```
18:54:45.577 [Log] : EOSManager: Registering for platform-specific notifications
<color=#FFFF00>18:54:45.617 [Warning] : EOSManager::Init: InitializePlatformInterface: initResult = Success</color>
<color=#FFFF00>18:54:45.634 [Warning] : 2023-09-26T14:54:45.6321559-04:00 LogEOSAuth(Warning): FAccountPortalBrowserManager::Init: Failed to register overlay: EOS_NotConfigured</color>
<color=#FFFF00>18:54:47.108 [Warning] : 2023-09-26T14:54:47.1076588-04:00 LogEOSAnalytics(Warning): EOS SDK Analytics disabled for route [1].</color>
18:55:26.861 [Log] : Attempting to login...
18:55:27.915 [Log] : UserData (OnQueryUserInfoCompleted): QueryUserInfo successful
18:55:27.992 [Log] : Connect Login Successful. [Success]
18:55:28.098 [Log] : Friends (QueryFriendsCallback): Query Friends Complete for user id: 85039fd444ff40e5aa6d8664fe8fce52
18:55:28.099 [Log] : Friends (QueryFriendsCallback): Number of friends: 0
18:55:28.117 [Log] : UserData (OnQueryUserInfoCompleted): QueryUserInfo successful
18:55:28.118 [Log] : Leaderboard (LeaderboardDefinitionsReceivedCallbackFn): Query Definitions Complete
18:55:30.574 [Log] : Leaderboard (LeaderboardRanksReceivedCallbackFn): Query Ranks Complete
18:55:30.576 [Log] : Display Leaderboard Records: Count=0
18:55:33.923 [Log] : Leaderboard (StatsIngestCallbackFn): Ingest Stats Complete
18:55:37.214 [Log] : Leaderboard (LeaderboardDefinitionsReceivedCallbackFn): Query Definitions Complete
18:55:38.928 [Log] : Leaderboard (LeaderboardRanksReceivedCallbackFn): Query Ranks Complete
18:55:38.929 [Log] : Display Leaderboard Records: Count=0
<color=#FFFF00>18:55:39.550 [Warning] : UILeaderboardMenu (ShowFriendsOnClick): No friends found.</color>
18:55:44.985 [Log] : Leaderboard (StatsIngestCallbackFn): Ingest Stats Complete
18:55:47.649 [Log] : Leaderboard (LeaderboardRanksReceivedCallbackFn): Query Ranks Complete
18:55:47.649 [Log] : Display Leaderboard Records: Count=0
18:55:49.594 [Log] : Leaderboard (LeaderboardDefinitionsReceivedCallbackFn): Query Definitions Complete
18:55:51.890 [Log] : Leaderboard (LeaderboardRanksReceivedCallbackFn): Query Ranks Complete
18:55:51.890 [Log] : Display Leaderboard Records: Count=0
18:55:52.559 [Log] : Leaderboard (LeaderboardRanksReceivedCallbackFn): Query Ranks Complete
18:55:52.560 [Log] : Display Leaderboard Records: Count=0
```

**Comment by paulhazen** [comment] 2023-09-26 20:23
> Yeah, it's both. I guess I can record it just to be clear: https://streamable.com/gwe193
> 
> This time the log is a bit longer because I clicked around more.
> 
> ```
> 18:54:45.577 [Log] : EOSManager: Registering for platform-specific notifications
> <color=#FFFF00>18:54:45.617 [Warning] : EOSManager::Init: InitializePlatformInterface: initResult = Success</color>
> <color=#FFFF00>18:54:45.634 [Warning] : 2023-09-26T14:54:45.6321559-04:00 LogEOSAuth(Warning): FAccountPortalBrowserManager::Init: Failed to register overlay: EOS_NotConfigured</color>
> <color=#FFFF00>18:54:47.108 [Warning] : 2023-09-26T14:54:47.1076588-04:00 LogEOSAnalytics(Warning): EOS SDK Analytics disabled for route [1].</color>
> 18:55:26.861 [Log] : Attempting to login...
> 18:55:27.915 [Log] : UserData (OnQueryUserInfoCompleted): QueryUserInfo successful
> 18:55:27.992 [Log] : Connect Login Successful. [Success]
> 18:55:28.098 [Log] : Friends (QueryFriendsCallback): Query Friends Complete for user id: 85039fd444ff40e5aa6d8664fe8fce52
> 18:55:28.099 [Log] : Friends (QueryFriendsCallback): Number of friends: 0
> 18:55:28.117 [Log] : UserData (OnQueryUserInfoCompleted): QueryUserInfo successful
> 18:55:28.118 [Log] : Leaderboard (LeaderboardDefinitionsReceivedCallbackFn): Query Definitions Complete
> 18:55:30.574 [Log] : Leaderboard (LeaderboardRanksReceivedCallbackFn): Query Ranks Complete
> 18:55:30.576 [Log] : Display Leaderboard Records: Count=0
> 18:55:33.923 [Log] : Leaderboard (StatsIngestCallbackFn): Ingest Stats Complete
> 18:55:37.214 [Log] : Leaderboard (LeaderboardDefinitionsReceivedCallbackFn): Query Definitions Complete
> 18:55:38.928 [Log] : Leaderboard (LeaderboardRanksReceivedCallbackFn): Query Ranks Complete
> 18:55:38.929 [Log] : Display Leaderboard Records: Count=0
> <color=#FFFF00>18:55:39.550 [Warning] : UILeaderboardMenu (ShowFriendsOnClick): No friends found.</color>
> 18:55:44.985 [Log] : Leaderboard (StatsIngestCallbackFn): Ingest Stats Complete
> 18:55:47.649 [Log] : Leaderboard (LeaderboardRanksReceivedCallbackFn): Query Ranks Complete
> 18:55:47.649 [Log] : Display Leaderboard Records: Count=0
> 18:55:49.594 [Log] : Leaderboard (LeaderboardDefinitionsReceivedCallbackFn): Query Definitions Complete
> 18:55:51.890 [Log] : Leaderboard (LeaderboardRanksReceivedCallbackFn): Query Ranks Complete
> 18:55:51.890 [Log] : Display Leaderboard Records: Count=0
> 18:55:52.559 [Log] : Leaderboard (LeaderboardRanksReceivedCallbackFn): Query Ranks Complete
> 18:55:52.560 [Log] : Display Leaderboard Records: Count=0
> ```

Have you checked the Leaderboards inside Epic's Development portal to make sure that each of the Leaderboards you are trying to add to have their status marked as `Active`? 

![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/1439891/4cf43dd6-b570-4ddc-b546-efcc670877a4)

I get the same behavior as you are experiencing when I try and ingest a stat for the expired Leaderboard `MaxStat_Dev`.

Subsequently, does the deployment for the leaderboard match the deployment you have defined in the plugin configuration?

![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/1439891/92cd4075-0fd1-4592-b9ec-0b00420f7735)

**Comment by 3ternal** [comment] 2023-09-27 16:04
Hey, good question - I hadn't thought to check the sandboxes. But, it looks like the leaderboards and the EOS Config Editor are both set to Dev (and leaderboards are active).

By the way, would this problem occur if something else is wrong in the Config Editor? I got my Client ID and Client Secret from the BPT Credentials tab on the Epic dev portal - is that correct?

**Comment by paulhazen** [comment] 2023-09-28 18:56
> Hey, good question - I hadn't thought to check the sandboxes. But, it looks like the leaderboards and the EOS Config Editor are both set to Dev (and leaderboards are active).
> 
> By the way, would this problem occur if something else is wrong in the Config Editor? I got my Client ID and Client Secret from the BPT Credentials tab on the Epic dev portal - is that correct?

That is correct. Interesting. It's difficult to reproduce this issue. :\

What happens if you use an account that has friends? It would be interesting if some component of leaderboard functionality was contingent upon having friends - interesting and wrong functionality IMO. But that's the only difference I can immediately see in the circumstances.

**Comment by 3ternal** [comment] 2023-09-28 19:04
> > Hey, good question - I hadn't thought to check the sandboxes. But, it looks like the leaderboards and the EOS Config Editor are both set to Dev (and leaderboards are active).
> > By the way, would this problem occur if something else is wrong in the Config Editor? I got my Client ID and Client Secret from the BPT Credentials tab on the Epic dev portal - is that correct?
> 
> That is correct. Interesting. It's difficult to reproduce this issue. :\
> 
> What happens if you use an account that has friends? It would be interesting if some component of leaderboard functionality was contingent upon having friends - interesting and wrong functionality IMO. But that's the only difference I can immediately see in the circumstances.

Actually, wait a minute. I _do_ have friends on that Epic account, but the log says no friends found. Is that an error? (My friends don't own the game or have access to the leaderboard, because it's not live). My account ID on the Epic website matches the one displayed in the log.

Do you have a test project or something like that? Does this work on your end (in 2.3.3)?

**Comment by paulhazen** [comment] 2023-09-28 21:45
That is strange. We do not have an externally available test project for this - because that would involve providing credentials for real epic online accounts. However, I can confirm that we have tested it with accounts that have friends, and it does work on `2.3.3`.

What happens if you use the account portal option to log in with, instead of PersistentAuth? Do you get the same results?

**Comment by 3ternal** [comment] 2023-09-29 13:50
Hmm, it looks like it's the same. The only difference is that there's a button that says "[log in to EOS using specified parameters](https://i.imgur.com/MyaN1EB.png)".

Well, I suppose it's not a priority for now, because the game isn't coming out just yet. One thing I've noticed is that I can't move my leaderboards from Dev to Stage - I see the button for achievements and stats, but not leaderboards. So I might as well ask Epic about that in the meantime. This whole problem might be one of those things that resolves itself once everything moves to Stage or Live (even if the leaderboard is Live, the game itself wouldn't be released, so that's probably still suitable for testing).

**Comment by 3ternal** [comment] 2023-10-05 14:09
Okay, I think we're good to go. Epic staff confirmed that they had a backend issue with Leaderboards, and it's resolved now. Looks like everything is working on my end now.

**Comment by paulhazen** [comment] 2023-10-09 19:10
@3ternal Glad to hear things are resolved - never hesitate to reach out to us! :)

**Closed by paulhazen** 2023-10-09 19:10 UTC
Labels: bug
