### ISSUE TITLE
Netcode for GameObjects - Kicking a client as a host also kicks the host. (only with EOSTransport)

### ISSUE THREAD

**Issue by nitrocss** [PlayEveryWare/eos_plugin_for_unity#508] opened 2024-01-08 08:03 UTC
Hey again,

I found a bug that I can't replicate with Unity Transport Layer. 
It seems the functionality to remove players is broken when using EOS Transport.

Repro:
I host the game, join with a client. I then kick the client using:
`NetworkManager.Singleton.DisconnectClient(otherClient.OwnerClientId);`

The client gets disconnected, but so does the host. I used debugger, and it seems that host player gets de-spawned at:
`internal void OnClientDisconnectFromServer(ulong clientId)`

I tested on Windows PC, with newest 3.0.2 EOS package.

**Comment by paulhazen** [comment] 2024-01-20 00:42
Hi @nitrocss, apologies for the much-delayed response. Are you still experiencing this problem?

Do you experience the same behavior if you have more than one client, and one of them is kicked? Or do you notice the behavior only when the last client is kicked? Knowing that could help narrow down the problem.

**Comment by nitrocss** [comment] 2024-01-21 06:16
Yes, the problem is still there.

> Do you experience the same behavior if you have more than one client, and one of them is kicked? Or do you notice the behavior only when the last client is kicked? Knowing that could help narrow down the problem.

I'm gonna test with another player today and let you know.

**Comment by nitrocss** [comment] 2024-01-22 15:57
I tested this with another player, and it seems that:

When host kicks another player, whether it is second or third player, host's player gets despawned (but he doesn't get disconnected), and the player getting kicked does get despawned and disconnected. I could still be playing with the non-kicked user as a client after host's player disappeared, and it was syncing everything. 

To sum it up:
1. Player A created a session as a host
2. Player B joined
3. Player C joined
4.  Player A kicked player C
5. Player A lost his bunny, Player C got disconnected. Player B is untouched and can keep playing.

Same scenario when kicking player B - then player C could still be playing.

**Comment by paulhazen** [comment] 2024-01-25 02:04
> Repro: I host the game, join with a client. I then kick the client using: `NetworkManager.Singleton.DisconnectClient(otherClient.OwnerClientId);`
> 
> The client gets disconnected, but so does the host. I used debugger, and it seems that host player gets de-spawned at: `internal void OnClientDisconnectFromServer(ulong clientId)`
> 

Can you clarify in which file each of the lines above are from (and the line number)? They don't appear to be signatures that are defined within the EOS Plugin.

**Comment by nitrocss** [comment] 2024-01-25 20:26
Much easier repro for this issue is to change this value in networkmanager inspector to 1 and try connecting (toggle checkbox so the field is editable). It will yield the same result (client fails to connect, so host kicks the client automatically, but it also kicks the host)

![298751837-3f24cc20-8c5d-4cf3-a95d-9a344caadae8](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/30451923/c8c46827-40c4-422c-a9e9-76f16f748c25)

**Comment by paulhazen** [comment] 2024-01-25 23:33
(I'm closing this issue as it's tied to #518, and the source of the issue is compatibility problems with newer versions of Netcode). This is a priority for us to fix, and we will update this thread when that work has been done.

**Closed by paulhazen** 2024-01-25 23:33 UTC
