### ISSUE TITLE
local player unable to see remote players' display names

### ISSUE THREAD

**Issue by superrafyYT** [PlayEveryWare/eos_plugin_for_unity#603] opened 2024-04-13 21:07 UTC
when joining a lobby, the local user isnt able to retrieve the remote users' display name, only the lobby host can see everyone's name

1. create a lobby
2. join a lobby with another device
3. the host is able to see the name of the player who joined, but the player who joined isnt able to see anybody's name other than his

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Editor
 - 2021.3.8f1
 - Release 3.0.3

**Smartphone (please complete the following information):**
 - Device: galaxy s20
 - OS: android 13
 - 2021.3.8f1
 - Release 3.0.3

**Comment by andrew-hirata-playeveryware** [comment] 2024-04-18 18:18
Interesting: I think I made another assumption: are you using our lobby samples? Or did you write your own? In our lobby samples I see that we add the username as lobby attribute and mark it as public, which should work as long as the user has a displayname set. If you are using the samples, you could try and send across the nickname instead. The method in the EOSLobbyManager where we set that value is called `AddLocalUserAttributes`.

If you wrote your own samples, are you able to share the code for the lobbies that you wrote?

**Comment by superrafyYT** [comment] 2024-04-19 07:32
@andrew-hirata-playeveryware im using a sample from this repo: https://github.com/FirstGearGames/FishyEOS

**Comment by superrafyYT** [comment] 2024-04-19 07:43
oh and sorry for the question, though may i know the limits for lobby voice chat? does that mean if there's more than 64 lobbies voice chat wont work?
and does it support android aswell?

**Comment by superrafyYT** [comment] 2024-04-19 20:36
![image](https://github.com/PlayEveryWare/eos_plugin_for_unity/assets/86516779/e73570da-77d1-432e-81e6-7197ff0a933b)
`DisplayName` doesnt works btw from the class: LobbyMember

**Comment by andrew-hirata-playeveryware** [comment] 2024-04-22 19:18
I don't know if I'll be able to help you too much as the bugs you're describing appear to be in their implementation, not with our plugin itself. Is it possible for you to reach out to the author of those samples? 

But I'll try to help anyway 😄 

From a quick reading of that sample, it doesn't look like the code actually grabs any real user display names or nicknames, which might be the cause of the issue. I think it just requires the user to type in the displayname, based on what I'm seeing in the `LobbyVariables.cs` file. You should be able to modify their code and substitute it with a call to grab the displayname from wherever you'd like. Our plugin has an example of how to grab that kind of info in the `EOSUserInfoManager` class. 

Hope that helps!

**Comment by skeyll** [comment] 2024-04-24 08:32
@superrafyYT
VC member limit is 16.

I looked at the sample, and it seems like the DisplayName isn't registering in the lobby. If the device logs in with the Auth API, it may register the DisplayName, but if it uses Connect, it probably won't set the DisplayName in EOS. (I don't use Auth, so I'm not certain about this.)
If you want to add the name to the lobby as a Member attribute, you can set it with an uppercase key and retrieve it using that key.

**Comment by andrew-hirata-playeveryware** [comment] 2024-04-27 00:31
Closing as this isn't a bug with our Plugin, but with samples not provided by our plugin. Feel free to continue the discussion or similar integration questions in our github discussions!

**Closed by andrew-hirata-playeveryware** 2024-04-27 00:31 UTC

**Comment by superrafyYT** [comment] 2024-05-01 10:06
hello @andrew-hirata-playeveryware yes i actually found a work around, and it works now, sorry for not repliying for days
